import { ImagesMap } from "@/types/recipe.types";

export const IMAGES: ImagesMap = {
  // Recipe Images
  egyptian_koshari: require("@/assets/images/dishes/koshari.jpg"),
  egyptian_molokhia: require("@/assets/images/dishes/molokhia.jpg"),
  egyptian_fatta: require("@/assets/images/dishes/fatta.jpg"),
  egyptian_okra: require("@/assets/images/dishes/okra.jpg"),
  egyptian_moussaka: require("@/assets/images/dishes/moussaka.jpg"),
  egyptian_mahshi: require("@/assets/images/dishes/mahshi.jpg"),
  egyptian_potato_stew: require("@/assets/images/dishes/potato-stew.jpg"),
  egyptian_fish: require("@/assets/images/dishes/fish.jpg"),
  egyptian_shrimp: require("@/assets/images/dishes/shrimp.jpg"),
  egyptian_seafood_tagen: require("@/assets/images/dishes/seafood-tagen.jpg"),
  egyptian_pigeon: require("@/assets/images/dishes/pigeon.jpg"),
  egyptian_kofta: require("@/assets/images/dishes/kofta.jpg"),
  egyptian_kebab: require("@/assets/images/dishes/kebab.jpg"),
  egyptian_chicken: require("@/assets/images/dishes/chicken.jpg"),
  egyptian_default: require("@/assets/images/dishes/pigeon.jpg"),

  // Resilient Recipe Images (أكلات الفراعنة )
  pharaonic_lentils: require("@/assets/images/pharaonic/lentils.jpg"),
  pharaonic_onion_soup: require("@/assets/images/pharaonic/onion-soup.jpg"),
  pharaonic_salad: require("@/assets/images/pharaonic/salad.jpg"),
  pharaonic_duck: require("@/assets/images/pharaonic/duck.jpg"),
  pharaonic_goose: require("@/assets/images/pharaonic/goose.jpg"),
  pharaonic_pigeon: require("@/assets/images/pharaonic/pigeon.jpg"),
  pharaonic_deer: require("@/assets/images/pharaonic/deer.jpeg"),
  pharaonic_grilled_fish: require("@/assets/images/pharaonic/grilled-fish.jpg"),
  pharaonic_dried_fish: require("@/assets/images/pharaonic/dried-fish.jpg"),
  pharaonic_fish_stew: require("@/assets/images/pharaonic/fish-stew.jpg"),
  pharaonic_default: require("@/assets/images/pharaonic/lentils.jpg"),
  
  // Appetizer Images
  appetizer_foul_medames: require("@/assets/images/appetizers/foul-medames.jpg"),
  appetizer_taameya: require("@/assets/images/appetizers/taameya.jpg"),
  appetizer_baba_ghanoush: require("@/assets/images/appetizers/baba-ghanoush.jpg"),
  appetizer_pickled_eggplant: require("@/assets/images/appetizers/pickled-eggplant.jpg"),
  appetizer_egg_omelette: require("@/assets/images/appetizers/egg-omelette.jpg"),
  appetizer_sambousek: require("@/assets/images/appetizers/sambousek.jpg"),
  appetizer_default: require("@/assets/images/appetizers/baba-ghanoush.jpg"),

  // Baked Images
  baked_baladi_bread: require("@/assets/images/bakery/baladi-bread.jpg"),
  baked_fino_kaiser: require("@/assets/images/bakery/fino-kaiser.jpg"),
  baked_oat_bread: require("@/assets/images/bakery/oat-bread.jpg"),
  baked_masboubah: require("@/assets/images/bakery/masboubah.jpg"),
  baked_feteer_meshaltet: require("@/assets/images/bakery/feteer-meshaltet.jpg"),
  baked_baton_saleh: require("@/assets/images/bakery/baton-saleh.jpg"),
  baked_manaqeesh: require("@/assets/images/bakery/manaqeesh.jpg"),
  baked_nawameh: require("@/assets/images/bakery/nawameh.jpg"),
  baked_baksamat: require("@/assets/images/bakery/baksamat.jpg"),
  baked_default: require("@/assets/images/bakery/baladi-bread.jpg"),

  // Dessert Images - الصور الجديدة المضافة
  dessert_egyptian_knafeh: require("@/assets/images/desserts/egyptian-knafeh.jpg"),
  dessert_basbousa: require("@/assets/images/desserts/basbousa.jpg"), // استخدام نفس صورة الكنافة النابلسية
  dessert_umm_ali: require("@/assets/images/desserts/umm-ali.jpg"),
  dessert_rice_pudding: require("@/assets/images/desserts/rice-pudding.jpg"),
  dessert_mehalabia: require("@/assets/images/desserts/mehalabia.jpg"),
  dessert_balah_alsham: require("@/assets/images/desserts/balah-alsham.jpg"),
  dessert_luqmat_alqadi: require("@/assets/images/desserts/luqmat-alqadi.jpg"),
  dessert_halawet_moulid: require("@/assets/images/desserts/halawet-moulid.jpg"),
  dessert_feteer_meshaltet: require("@/assets/images/desserts/feteer-meshaltet.jpg"),
  dessert_aysh_saraya: require("@/assets/images/desserts/aysh-saraya.jpg"),
  dessert_filled_balah_alsham: require("@/assets/images/desserts/balah-alsham.jpg"),
  dessert_candy_floss: require("@/assets/images/desserts/candy-floss.jpg"),
  dessert_sweet_pumpkin: require("@/assets/images/desserts/sweet-pumpkin.jpg"),
  dessert_kahk_eid: require("@/assets/images/desserts/kahk-eid.jpg"),
  dessert_default: require("@/assets/images/drinks/tamar-hindi.jpg"),

  // Drink Images
  drink_tamar_hindi: require("@/assets/images/drinks/tamar-hindi.jpg"),
  drink_karkadeh: require("@/assets/images/drinks/karkadeh.jpg"),
  drink_arqsoos: require("@/assets/images/drinks/arqsoos.jpg"),
  drink_sobya: require("@/assets/images/drinks/sobya.jpg"),
  drink_sugarcane: require("@/assets/images/drinks/sugarcane.jpg"),
  drink_orange_juice: require("@/assets/images/drinks/orange-juice.jpg"),
  drink_mango_juice: require("@/assets/images/drinks/mango-juice.jpg"),
  drink_strawberry_juice: require("@/assets/images/drinks/strawberry-juice.jpg"),
  drink_black_tea: require("@/assets/images/drinks/black-tea.jpg"),
  drink_default: require("@/assets/images/drinks/tamar-hindi.jpg"),

  // Salad Images
  salad_rocket: require("@/assets/images/salads/rocket.jpg"),
  salad_tahini: require("@/assets/images/salads/tahini.jpg"),
  salad_eggplant: require("@/assets/images/salads/eggplant.jpg"),
  salad_tomato_onion: require("@/assets/images/salads/tomato-onion.jpg"),
  salad_cabbage: require("@/assets/images/salads/cabbage.jpg"),
  salad_potato: require("@/assets/images/salads/potato.jpg"),
  salad_mixed_cabbage: require("@/assets/images/salads/mixed-cabbage.jpg"),
  salad_carrot_corn: require("@/assets/images/salads/carrot-corn.jpg"),
  salad_cucumber_mint: require("@/assets/images/salads/cucumber-mint.jpg"),
  salad_radish_parsley: require("@/assets/images/salads/radish-parsley.jpg"),
  salad_default: require("@/assets/images/salads/cabbage.jpg"),
};
