import { BaseRecipe } from "@/types/recipe.types";

export const APPETIZERS_AR: BaseRecipe[] = [
  {
    id: 1,
    title: "فول مدمس",
    image: "appetizer_foul_medames",
    description:
      "طبق فول مدمس مصري يقدم كوجبة فطور رئيسية أو كمقبلات، يُقدّم مع زيت الزيتون والليمون والخبز.",
    time: "20 دقيقة",
    difficulty: "سهل",
    servings: "4 أشخاص",
    ingredients: [
      "2 كوب فول مدشوش مسلوق",
      "2 ملعقة كبيرة زيت زيتون",
      "عصير ليمونة",
      "ملح وفلفل حسب الرغبة",
      "ثوم مهروس (اختياري)",
    ],
    steps: [
      "سخن الفول المسلوق في قدر مع قليل من الماء إذا لزم.",
      "أضف عصير الليمون وزيت الزيتون والملح والفلفل.",
      "اخلط جيدًا وقدمه دافئًا مع الخبز.",
    ],
  },
  {
    id: 2,
    title: "طعمية (فلافل)",
    image: "appetizer_taameya",
    description:
      "أقراص الفول المهروس والمقلية، تُقدّم كمقبلات في الإفطار أو كوجبة خفيفة، ويوجد أنواع مثل الطعمية الإسكندراني المحشوة.",
    time: "40 دقيقة",
    difficulty: "متوسطة",
    servings: "4 أشخاص",
    ingredients: [
      "2 كوب فول مدشوش منقوع",
      "بقدونس مفروم",
      "بصل أخضر مفروم",
      "ثوم مهروس",
      "ملح وفلفل",
      "زيت للقلي",
    ],
    steps: [
      "اطحن الفول المنقوع مع البقدونس والبصل والثوم والتوابل حتى يصبح عجينة ناعمة.",
      "شكل العجينة على شكل أقراص صغيرة.",
      "سخن الزيت واقلي الطعمية حتى تصبح ذهبية.",
      "قدّمها ساخنة مع الطحينة أو الخبز.",
    ],
  },
  {
    id: 3,
    title: "بابا غنوج",
    image: "appetizer_baba_ghanoush",
    description:
      "باذنجان مشوي مهروس مع الطحينة والثوم وعصير الليمون، من أشهر المقبلات المصرية.",
    time: "30 دقيقة",
    difficulty: "سهل",
    servings: "4 أشخاص",
    ingredients: [
      "2 حبة باذنجان كبيرة",
      "3 ملاعق كبيرة طحينة",
      "2 فص ثوم مهروس",
      "عصير ليمونة",
      "ملح وفلفل",
      "زيت زيتون للتزيين",
    ],
    steps: [
      "اشوي الباذنجان حتى يلين تمامًا ثم قشره واهرسه.",
      "اخلط الباذنجان المهروس مع الطحينة والثوم وعصير الليمون والملح والفلفل.",
      "زين بزيت الزيتون وقدمه مع الخبز.",
    ],
  },
  {
    id: 4,
    title: "مخلل الباذنجان",
    image: "appetizer_pickled_eggplant",
    description:
      "باذنجان مخلل مع الثوم والفلفل، يُقدم كمقبلات جانبية في الوجبات المصرية.",
    time: "3 أيام للتحضير",
    difficulty: "متوسطة",
    servings: "4 أشخاص",
    ingredients: [
      "4 حبات باذنجان صغيرة",
      "4 فصوص ثوم",
      "1 فلفل حار",
      "ملح",
      "خل",
      "زيت زيتون للحفظ",
    ],
    steps: [
      "اغسل الباذنجان وثقبه قليلاً.",
      "ضع الباذنجان في محلول ملح واتركه يومًا للتخلص من الطعم المر.",
      "اغلي الخل مع الملح واسكب فوق الباذنجان مع الثوم والفلفل.",
      "حفظه في برطمان مع الزيت لعدة أيام قبل التقديم.",
    ],
  },
  {
    id: 5,
    title: "الكشك",
    image: "appetizer_kishk",
    description:
      "خليط من البيض والدقيق والبصل متبل بالبهارات، يُقدم كمقبلات مصرية خفيفة.",
    time: "25 دقيقة",
    difficulty: "سهل",
    servings: "4 أشخاص",
    ingredients: [
      "3 بيضات",
      "2 ملعقة كبيرة دقيق",
      "1 بصلة صغيرة مفرومة",
      "ملح وفلفل حسب الرغبة",
      "زيت للقلي",
    ],
    steps: [
      "اخفق البيض مع الدقيق والبصل والملح والفلفل.",
      "سخن الزيت واقلي الخليط على شكل فطائر صغيرة.",
      "قدمه دافئًا كمقبلات.",
    ],
  },
  {
    id: 6,
    title: "العجة",
    image: "appetizer_egg_omelette",
    description:
      "بيض مخلوط بالبقدونس والبصل الأخضر مع الدقيق والبهارات، يُقدّم كمقبلات سريعة.",
    time: "15 دقيقة",
    difficulty: "سهل",
    servings: "4 أشخاص",
    ingredients: [
      "4 بيضات",
      "بقدونس مفروم",
      "بصل أخضر مفروم",
      "1 ملعقة كبيرة دقيق",
      "ملح وفلفل حسب الرغبة",
      "زيت للقلي",
    ],
    steps: [
      "اخلط البيض مع البقدونس والبصل والدقيق والملح والفلفل.",
      "سخن الزيت واقلي المزيج على شكل أقراص صغيرة.",
      "قدمه دافئًا كمقبلات.",
    ],
  },
  {
    id: 7,
    title: "السمبوسك",
    image: "appetizer_sambousek",
    description:
      "عجينة محشوة بالجبن أو اللحم أو الخضار ومقلية، تُقدّم كمقبلات مصرية شهيرة.",
    time: "30 دقيقة",
    difficulty: "متوسطة",
    servings: "4 أشخاص",
    ingredients: [
      "10 ورقات عجينة سمبوسك",
      "حشوة جبن أو لحم مفروم أو خضار",
      "زيت للقلي",
      "بهارات حسب الرغبة",
    ],
    steps: [
      "احشي ورقة العجين بالحشوة المختارة واغلقها جيدًا.",
      "سخن الزيت واقلي السمبوسك حتى يصبح ذهبي اللون.",
      "قدمه ساخنًا كمقبلات.",
    ],
  },
];

export const APPETIZERS_EN: BaseRecipe[] = [
  {
    id: 1,
    title: "Foul Medames",
    image: "appetizer_foul_medames",
    description:
      "A classic Egyptian fava bean dish served as breakfast or appetizer, typically with olive oil, lemon, and bread.",
    time: "20 minutes",
    difficulty: "Easy",
    servings: "4 servings",
    ingredients: [
      "2 cups cooked fava beans",
      "2 tbsp olive oil",
      "Juice of 1 lemon",
      "Salt and pepper to taste",
      "Optional: minced garlic",
    ],
    steps: [
      "Heat the cooked fava beans in a pot, adding a little water if needed.",
      "Add lemon juice, olive oil, salt, and pepper.",
      "Mix well and serve warm with bread.",
    ],
  },
  {
    id: 2,
    title: "Taameya (Egyptian Falafel)",
    image: "appetizer_taameya",
    description:
      "Mashed fava bean patties, fried and served as an appetizer or snack. Variants include Alexandrian stuffed falafel.",
    time: "40 minutes",
    difficulty: "Medium",
    servings: "4 servings",
    ingredients: [
      "2 cups soaked fava beans",
      "Chopped parsley",
      "Chopped green onions",
      "Minced garlic",
      "Salt and pepper",
      "Oil for frying",
    ],
    steps: [
      "Grind soaked fava beans with parsley, green onions, garlic, and spices until smooth.",
      "Shape the mixture into small patties.",
      "Heat oil and fry the patties until golden.",
      "Serve hot with tahini or bread.",
    ],
  },
  {
    id: 3,
    title: "Baba Ghanoush",
    image: "appetizer_baba_ghanoush",
    description:
      "Roasted eggplant mashed with tahini, garlic, and lemon juice, a popular Egyptian appetizer.",
    time: "30 minutes",
    difficulty: "Easy",
    servings: "4 servings",
    ingredients: [
      "2 large eggplants",
      "3 tbsp tahini",
      "2 cloves garlic, minced",
      "Juice of 1 lemon",
      "Salt and pepper",
      "Olive oil for garnish",
    ],
    steps: [
      "Roast the eggplants until tender, peel and mash.",
      "Mix mashed eggplant with tahini, garlic, lemon juice, salt, and pepper.",
      "Garnish with olive oil and serve with bread.",
    ],
  },
  {
    id: 4,
    title: "Pickled Eggplant",
    image: "appetizer_pickled_eggplant",
    description:
      "Pickled eggplants with garlic and chili peppers, served as a side appetizer in Egyptian meals.",
    time: "3 days preparation",
    difficulty: "Medium",
    servings: "4 servings",
    ingredients: [
      "4 small eggplants",
      "4 cloves garlic",
      "1 hot chili pepper",
      "Salt",
      "Vinegar",
      "Olive oil for storage",
    ],
    steps: [
      "Wash the eggplants and prick them slightly.",
      "Soak in salted water for a day to remove bitterness.",
      "Boil vinegar with salt and pour over eggplants with garlic and chili.",
      "Store in a jar with oil for a few days before serving.",
    ],
  },
  {
    id: 5,
    title: "Kishk",
    image: "appetizer_kishk",
    description:
      "A mixture of eggs, flour, and onion, seasoned with spices, served as a light Egyptian appetizer.",
    time: "25 minutes",
    difficulty: "Easy",
    servings: "4 servings",
    ingredients: [
      "3 eggs",
      "2 tbsp flour",
      "1 small onion, chopped",
      "Salt and pepper",
      "Oil for frying",
    ],
    steps: [
      "Beat eggs with flour, onion, salt, and pepper.",
      "Heat oil and fry the mixture into small patties.",
      "Serve warm as an appetizer.",
    ],
  },
  {
    id: 6,
    title: "Egg Omelette (Eja)",
    image: "appetizer_egg_omelette",
    description:
      "Eggs mixed with parsley and green onions, with flour and spices, served as a quick appetizer.",
    time: "15 minutes",
    difficulty: "Easy",
    servings: "4 servings",
    ingredients: [
      "4 eggs",
      "Chopped parsley",
      "Chopped green onions",
      "1 tbsp flour",
      "Salt and pepper",
      "Oil for frying",
    ],
    steps: [
      "Mix eggs with parsley, green onions, flour, salt, and pepper.",
      "Heat oil and fry the mixture into small rounds.",
      "Serve warm as an appetizer.",
    ],
  },
  {
    id: 7,
    title: "Sambousek",
    image: "appetizer_sambousek",
    description:
      "Dough filled with cheese, minced meat, or vegetables, fried and served as a popular Egyptian appetizer.",
    time: "30 minutes",
    difficulty: "Medium",
    servings: "4 servings",
    ingredients: [
      "10 sheets of sambousek dough",
      "Filling: cheese, minced meat, or vegetables",
      "Oil for frying",
      "Spices as desired",
    ],
    steps: [
      "Fill dough sheets with the chosen filling and seal well.",
      "Heat oil and fry sambousek until golden brown.",
      "Serve hot as an appetizer.",
    ],
  },
];
