import { BaseRecipe } from "@/types/recipe.types";

export const DESSERTS_AR: BaseRecipe[]= 
[
  {
    id: 1,
    title: "كنافة مصرية",
    image: "dessert_egyptian_knafeh",
    description:
      "حلوى مصرية مشهورة من الكنافة المقرمشة والجبن الحلو مع القطر، تقدم في المناسبات والأعياد.",
    time: "45 دقيقة",
    difficulty: "متوسطة",
    servings: "6 أشخاص",
    ingredients: [
      "500 غرام كنافة",
      "300 غرام جبنة حلويات أو نابلسية",
      "1 كوب سمن أو زبدة مذابة",
      "2 كوب قطر",
      "فستق حلبي للتزيين",
    ],
    steps: [
      "نفتت الكنافة ونخلطها مع السمن المذاب.",
      "نضع نصف كمية الكنافة في صينية ونضغطها جيدًا.",
      "نضيف طبقة الجبن فوقها ثم نغطيها بالنصف الآخر من الكنافة.",
      "نخبزها حتى تكتسب لونًا ذهبيًا.",
      "نسكب القطر فوقها ونزين بالفستق الحلبي.",
    ],
  },
  {
    id: 2,
    title: "بسبوسة",
    image: "dessert_basbousa",
    description:
      "حلوى سميدية مصرية تقليدية مغطاة بالقطر، وغالبًا تُزين بالمكسرات.",
    time: "50 دقيقة",
    difficulty: "متوسطة",
    servings: "8 أشخاص",
    ingredients: [
      "2 كوب سميد",
      "1 كوب سكر",
      "1 كوب جوز هند",
      "1 كوب لبن",
      "نصف كوب سمن",
      "2 كوب قطر",
    ],
    steps: [
      "اخلط السميد مع جوز الهند والسكر والسمن.",
      "أضف اللبن وحرك جيدًا.",
      "ضع الخليط في صينية مدهونة.",
      "اخبزها حتى يصبح لونها ذهبيًا.",
      "اسكب القطر بعد إخراجها من الفرن.",
    ],
  },
  {
    id: 3,
    title: "أم علي",
    image: "dessert_umm_ali",
    description:
      "حلوى شعبية مصرية من رقائق العجين أو الخبز مع الحليب والمكسرات، تُقدم ساخنة.",
    time: "40 دقيقة",
    difficulty: "سهلة",
    servings: "6 أشخاص",
    ingredients: [
      "5 وحدات كرواسون أو رقائق عجين",
      "1 لتر حليب",
      "1 كوب سكر",
      "1 كوب مكسرات مشكلة",
      "زبيب وجوز هند",
    ],
    steps: [
      "قطّع الكرواسون أو العجين إلى قطع صغيرة.",
      "ضعها في صينية وأضف المكسرات والزبيب.",
      "اسكب الحليب الساخن الممزوج بالسكر فوقها.",
      "ضع الصينية في الفرن حتى تتحمر الوجه.",
      "قدّمها ساخنة.",
    ],
  },
  {
    id: 4,
    title: "أرز باللبن",
    image: "dessert_rice_pudding",
    description:
      "حلوى مصرية بسيطة مصنوعة من الأرز بالحليب والسكر وتُزين بالقرفة أو المكسرات.",
    time: "35 دقيقة",
    difficulty: "سهلة",
    servings: "4 أشخاص",
    ingredients: [
      "1 كوب أرز",
      "4 أكواب حليب",
      "نصف كوب سكر",
      "1 ملعقة صغيرة فانيليا",
      "قرفة أو مكسرات للتزيين",
    ],
    steps: [
      "اسلق الأرز نصف سلق.",
      "أضف الحليب والسكر واتركه على النار حتى يغلظ القوام.",
      "أضف الفانيليا وحرك جيدًا.",
      "اسكبه في أطباق صغيرة.",
      "زين بالقرفة أو المكسرات.",
    ],
  },
  {
    id: 5,
    title: "مهلبية",
    image: "dessert_mehalabia",
    description:
      "حلوى كريمية سهلة التحضير من الحليب والنشا، تُقدم باردة ومزينة بالمكسرات.",
    time: "20 دقيقة",
    difficulty: "سهلة",
    servings: "4 أشخاص",
    ingredients: [
      "4 أكواب حليب",
      "4 ملاعق نشا",
      "نصف كوب سكر",
      "1 ملعقة صغيرة فانيليا",
      "فستق أو جوز هند للتزيين",
    ],
    steps: [
      "اخلط الحليب مع النشا والسكر.",
      "ضع الخليط على نار متوسطة مع التحريك حتى يتماسك.",
      "أضف الفانيليا.",
      "اسكب في أطباق صغيرة واتركه يبرد.",
      "زين بالفستق أو جوز الهند.",
    ],
  },
  {
    id: 6,
    title: "بلح الشام",
    image: "dessert_balah_alsham",
    description:
      "حلوى مقلية مقرمشة مغموسة في القطر، من أشهر الحلويات المصرية الشعبية.",
    time: "45 دقيقة",
    difficulty: "متوسطة",
    servings: "6 أشخاص",
    ingredients: [
      "2 كوب دقيق",
      "2 كوب ماء",
      "نصف كوب زيت",
      "4 بيضات",
      "رشة فانيليا",
      "2 كوب قطر",
    ],
    steps: [
      "اغلِ الماء والزيت ثم أضف الدقيق وحرك حتى تتماسك العجينة.",
      "دعها تبرد قليلًا ثم أضف البيض والفانيليا تدريجيًا.",
      "ضع العجينة في كيس حلواني وشكّل أصابع.",
      "اقلِها في زيت غزير حتى تحمر.",
      "اغمسها مباشرة في القطر.",
    ],
  },
  {
    id: 7,
    title: "زلابية (لقمة القاضي)",
    image: "dessert_luqmat_alqadi",
    description:
      "كرات عجين مقلية مغطاة بالقطر، حلوى شعبية مشهورة في مصر.",
    time: "30 دقيقة",
    difficulty: "سهلة",
    servings: "5 أشخاص",
    ingredients: [
      "2 كوب دقيق",
      "1 ملعقة صغيرة خميرة",
      "1 ملعقة صغيرة سكر",
      "1 كوب ماء دافئ",
      "زيت للقلي",
      "قطر أو عسل للتقديم",
    ],
    steps: [
      "اخلط الدقيق مع الخميرة والسكر والماء واتركه يختمر نصف ساعة.",
      "سخن الزيت واقلي العجينة على شكل كرات صغيرة.",
      "اغمسها في القطر أو العسل فور إخراجها من الزيت.",
    ],
  },
 
  {
    id: 9,
    title: "حلاوة المولد",
    image: "dessert_halawet_moulid",
    description:
      "حلويات متنوعة تُصنع من السمسم والفول السوداني واللوز والحمص، تقدم في المولد النبوي.",
    time: "60 دقيقة",
    difficulty: "متوسطة",
    servings: "8 أشخاص",
    ingredients: [
      "1 كوب سمسم",
      "1 كوب سكر",
      "نصف كوب فول سوداني أو لوز",
      "ماء للقطر",
    ],
    steps: [
      "حمص السمسم والمكسرات قليلًا.",
      "أضف السكر والماء لتشكيل القطر.",
      "اصنع أصابع أو كرات صغيرة بالسمسم والمكسرات.",
      "اغمسها في القطر إذا رغبت.",
    ],
  },
  {
    id: 10,
    title: "فطير مشلتت بالعسل",
    image: "dessert_feteer_meshaltet",
    description:
      "فطير مصري تقليدي يقدم مع العسل أو السكر، هش ولذيذ.",
    time: "50 دقيقة",
    difficulty: "متوسطة",
    servings: "6 أشخاص",
    ingredients: [
      "500 غرام دقيق",
      "250 غرام زبدة أو سمن",
      "1 كوب ماء",
      "عسل أو سكر للتقديم",
    ],
    steps: [
      "اعجن الدقيق مع الزبدة والماء حتى تتكون عجينة طرية.",
      "افردها واخبزها في الفرن أو على صاج.",
      "قطعها وقدمها مع العسل أو السكر.",
    ],
  },
  {
    id: 11,
    title: "عيش السرايا",
    image: "dessert_aysh_saraya",
    description:
      "حلوى شرقية تتكون من خبز محمص مع القشطة والقطر، غنية ومناسبة للمناسبات.",
    time: "45 دقيقة",
    difficulty: "متوسطة",
    servings: "6 أشخاص",
    ingredients: [
      "خبز محمص",
      "قشطة أو كريمة",
      "2 كوب قطر",
      "فستق للتزيين",
    ],
    steps: [
      "ضع الخبز المحمص في صينية.",
      "أضف طبقة القشطة فوقه.",
      "اسكب القطر بالتساوي.",
      "زين بالفستق الحلبي.",
      "قدمه باردًا أو في درجة حرارة الغرفة.",
    ],
  },

  {
    id: 12,
    title: "بلح الشام المحشو",
    image: "dessert_filled_balah_alsham",
    description:
      "نسخة متقدمة من بلح الشام، محشو بالقشطة أو المكسرات، مغطى بالقطر.",
    time: "50 دقيقة",
    difficulty: "متوسطة",
    servings: "6 أشخاص",
    ingredients: [
      "2 كوب دقيق",
      "2 كوب ماء",
      "نصف كوب زيت",
      "4 بيضات",
      "حشوة قشطة أو مكسرات",
      "2 كوب قطر",
    ],
    steps: [
      "حضّر عجينة بلح الشام التقليدية.",
      "اشكل العجينة على شكل أصابع وأضف الحشوة في المنتصف.",
      "اقلِها في زيت ساخن حتى تتحمر.",
      "اغمسها في القطر مباشرة بعد القلي.",
    ],
  },
  {
    id: 13,
    title: "غزل البنات",
    image: "dessert_candy_floss",
    description:
      "حلوى خفيفة من السكر المسحوب على شكل خيوط رفيعة، محبوبة للأطفال والكبار.",
    time: "20 دقيقة",
    difficulty: "سهلة",
    servings: "4 أشخاص",
    ingredients: [
      "2 كوب سكر",
      "1/4 كوب ماء",
      "ملونات طبيعية (اختياري)",
    ],
    steps: [
      "اغلِ السكر مع الماء حتى يتحول إلى شراب كثيف.",
      "اسحبه على خيوط رفيعة باستخدام شوكة أو أداة خاصة.",
      "شكل الخيوط على شكل كرات أو أعواد.",
      "قدمه للأطفال أو كزينة للحلويات الأخرى.",
    ],
  },
  {
    id: 14,
    title: "قرع عسلي باللبن",
    image: "dessert_sweet_pumpkin",
    description:
      "حلوى مصرية مصنوعة من القرع المحلى بالسكر أو العسل، تقدم مع الحليب أو الكريمة.",
    time: "40 دقيقة",
    difficulty: "سهلة",
    servings: "5 أشخاص",
    ingredients: [
      "500 غرام قرع",
      "1 كوب سكر أو عسل",
      "1 كوب حليب",
      "رشة قرفة",
    ],
    steps: [
      "اغسل وقطع القرع إلى مكعبات.",
      "اسلقه مع السكر أو العسل حتى ينضج.",
      "أضف الحليب والقرفة واطبخ 5 دقائق إضافية.",
      "قدمه دافئًا أو باردًا.",
    ],
  },
  {
    id: 15,
    title: "كحك العيد",
    image: "dessert_kahk_eid",
    description:
      "بسكويت هش محشو بالتمر أو المكسرات، يُرش بالسكر البودرة، ويعد من الحلويات التقليدية للعيد.",
    time: "60 دقيقة",
    difficulty: "متوسطة",
    servings: "10 أشخاص",
    ingredients: [
      "500 غرام دقيق",
      "250 غرام سمن",
      "1 كوب سكر",
      "حشوة تمر أو مكسرات",
      "سكر بودرة للتزيين",
    ],
    steps: [
      "اعجن الدقيق مع السمن والسكر حتى تتكون عجينة متماسكة.",
      "افرد العجينة واقطع دوائر صغيرة.",
      "ضع الحشوة في المنتصف وأغلقها.",
      "اخبزها في الفرن حتى تحمر.",
      "رش السكر البودرة بعد التبريد.",
    ],
  },
  

];



export const DESSERTS_EN: BaseRecipe[] = [
  {
    id: 1,
    title: "Egyptian Kunafa",
    image: "dessert_egyptian_knafeh",
    description:
      "Famous Egyptian dessert made from crispy kunafa pastry with sweet cheese and syrup, served on special occasions and holidays.",
    time: "45 min",
    difficulty: "Medium",
    servings: "6 people",
    ingredients: [
      "500 g kunafa",
      "300 g sweet cheese or Nabulsi cheese",
      "1 cup melted ghee or butter",
      "2 cups syrup",
      "Pistachios for garnish",
    ],
    steps: [
      "Crumble the kunafa and mix with melted ghee.",
      "Place half of the kunafa in a tray and press well.",
      "Add the cheese layer on top, then cover with the remaining kunafa.",
      "Bake until golden.",
      "Pour syrup on top and garnish with pistachios.",
    ],
  },
  {
    id: 2,
    title: "Basbousa",
    image: "dessert_basbousa",
    description:
      "Traditional Egyptian semolina cake soaked with syrup, often garnished with nuts.",
    time: "50 min",
    difficulty: "Medium",
    servings: "8 people",
    ingredients: [
      "2 cups semolina",
      "1 cup sugar",
      "1 cup desiccated coconut",
      "1 cup milk",
      "1/2 cup ghee",
      "2 cups syrup",
    ],
    steps: [
      "Mix semolina with coconut, sugar, and ghee.",
      "Add milk and stir well.",
      "Pour the mixture into a greased tray.",
      "Bake until golden.",
      "Pour syrup after removing from oven.",
    ],
  },
  {
    id: 3,
    title: "Umm Ali",
    image: "dessert_umm_ali",
    description:
      "Popular Egyptian dessert made from pastry layers or bread with milk and nuts, served warm.",
    time: "40 min",
    difficulty: "Easy",
    servings: "6 people",
    ingredients: [
      "5 croissants or pastry sheets",
      "1 liter milk",
      "1 cup sugar",
      "1 cup mixed nuts",
      "Raisins and coconut",
    ],
    steps: [
      "Cut croissants or pastry into small pieces.",
      "Place in a tray and add nuts and raisins.",
      "Pour hot milk mixed with sugar over them.",
      "Bake until the top browns.",
      "Serve warm.",
    ],
  },
  {
    id: 4,
    title: "Rice Pudding",
    image: "dessert_rice_pudding",
    description:
      "Simple Egyptian dessert made from rice cooked in milk and sugar, garnished with cinnamon or nuts.",
    time: "35 min",
    difficulty: "Easy",
    servings: "4 people",
    ingredients: [
      "1 cup rice",
      "4 cups milk",
      "1/2 cup sugar",
      "1 tsp vanilla",
      "Cinnamon or nuts for garnish",
    ],
    steps: [
      "Parboil the rice.",
      "Add milk and sugar, cook until thickened.",
      "Add vanilla and stir well.",
      "Pour into small dishes.",
      "Garnish with cinnamon or nuts.",
    ],
  },
  {
    id: 5,
    title: "Mehalabia",
    image: "dessert_mehalabia",
    description:
      "Creamy and easy-to-make dessert from milk and cornstarch, served chilled and garnished with nuts.",
    time: "20 min",
    difficulty: "Easy",
    servings: "4 people",
    ingredients: [
      "4 cups milk",
      "4 tbsp cornstarch",
      "1/2 cup sugar",
      "1 tsp vanilla",
      "Pistachios or coconut for garnish",
    ],
    steps: [
      "Mix milk with cornstarch and sugar.",
      "Cook on medium heat, stirring until thickened.",
      "Add vanilla.",
      "Pour into small dishes and let cool.",
      "Garnish with pistachios or coconut.",
    ],
  },
  {
    id: 6,
    title: "Balah El Sham",
    image: "dessert_balah_alsham",
    description:
      "Crispy fried dessert soaked in syrup, one of the most popular Egyptian sweets.",
    time: "45 min",
    difficulty: "Medium",
    servings: "6 people",
    ingredients: [
      "2 cups flour",
      "2 cups water",
      "1/2 cup oil",
      "4 eggs",
      "A pinch of vanilla",
      "2 cups syrup",
    ],
    steps: [
      "Boil water and oil, then add flour and stir until dough forms.",
      "Let it cool slightly, then gradually add eggs and vanilla.",
      "Pipe the dough into finger shapes.",
      "Fry in hot oil until golden.",
      "Dip immediately in syrup.",
    ],
  },
  {
    id: 7,
    title: "Luqmat Al-Qadi (Zalabia)",
    image: "dessert_luqmat_alqadi",
    description:
      "Fried dough balls coated in syrup, a popular Egyptian sweet.",
    time: "30 min",
    difficulty: "Easy",
    servings: "5 people",
    ingredients: [
      "2 cups flour",
      "1 tsp yeast",
      "1 tsp sugar",
      "1 cup warm water",
      "Oil for frying",
      "Syrup or honey for serving",
    ],
    steps: [
      "Mix flour with yeast, sugar, and water, leave to rise 30 min.",
      "Heat oil and fry small dough balls.",
      "Dip immediately in syrup or honey.",
    ],
  },
  {
    id: 9,
    title: "Moulid Sweets",
    image: "dessert_halawet_moulid",
    description:
      "Variety of sweets made from sesame, peanuts, almonds, or chickpeas, served during Moulid celebrations.",
    time: "60 min",
    difficulty: "Medium",
    servings: "8 people",
    ingredients: [
      "1 cup sesame seeds",
      "1 cup sugar",
      "1/2 cup peanuts or almonds",
      "Water for syrup",
    ],
    steps: [
      "Toast sesame and nuts slightly.",
      "Add sugar and water to make syrup.",
      "Form small sticks or balls with sesame and nuts.",
      "Dip in syrup if desired.",
    ],
  },
  {
    id: 10,
    title: "Feteer Meshaltet with Honey",
    image: "dessert_feteer_meshaltet",
    description:
      "Traditional Egyptian flaky pastry served with honey or sugar, soft and delicious.",
    time: "50 min",
    difficulty: "Medium",
    servings: "6 people",
    ingredients: [
      "500 g flour",
      "250 g butter or ghee",
      "1 cup water",
      "Honey or sugar for serving",
    ],
    steps: [
      "Knead flour with butter and water to form soft dough.",
      "Roll out and bake in oven or on a griddle.",
      "Cut and serve with honey or sugar.",
    ],
  },
  {
    id: 11,
    title: "Aish El-Saraya",
    image: "dessert_aysh_saraya",
    description:
      "Middle Eastern dessert made from toasted bread with cream and syrup, rich and perfect for special occasions.",
    time: "45 min",
    difficulty: "Medium",
    servings: "6 people",
    ingredients: [
      "Toasted bread",
      "Cream",
      "2 cups syrup",
      "Pistachios for garnish",
    ],
    steps: [
      "Place toasted bread in a tray.",
      "Add a layer of cream on top.",
      "Pour syrup evenly.",
      "Garnish with pistachios.",
      "Serve cold or at room temperature.",
    ],
  },
  {
    id: 12,
    title: "Filled Balah El Sham",
    image: "dessert_filled_balah_alsham",
    description:
      "Advanced version of Balah El Sham, filled with cream or nuts and soaked in syrup.",
    time: "50 min",
    difficulty: "Medium",
    servings: "6 people",
    ingredients: [
      "2 cups flour",
      "2 cups water",
      "1/2 cup oil",
      "4 eggs",
      "Filling: cream or nuts",
      "2 cups syrup",
    ],
    steps: [
      "Prepare traditional Balah El Sham dough.",
      "Shape dough into fingers and add filling inside.",
      "Fry in hot oil until golden.",
      "Dip immediately in syrup.",
    ],
  },
  {
    id: 13,
    title: "Cotton Candy",
    image: "dessert_candy_floss",
    description:
      "Light dessert made from pulled sugar into thin threads, loved by children and adults.",
    time: "20 min",
    difficulty: "Easy",
    servings: "4 people",
    ingredients: [
      "2 cups sugar",
      "1/4 cup water",
      "Optional natural coloring",
    ],
    steps: [
      "Boil sugar with water until thick syrup forms.",
      "Pull into thin threads using a fork or special tool.",
      "Shape into balls or sticks.",
      "Serve to children or as decoration for other desserts.",
    ],
  },
  {
    id: 14,
    title: "Sweet Pumpkin with Milk",
    image: "dessert_sweet_pumpkin",
    description:
      "Egyptian dessert made from pumpkin sweetened with sugar or honey, served with milk or cream.",
    time: "40 min",
    difficulty: "Easy",
    servings: "5 people",
    ingredients: [
      "500 g pumpkin",
      "1 cup sugar or honey",
      "1 cup milk",
      "A pinch of cinnamon",
    ],
    steps: [
      "Wash and cut pumpkin into cubes.",
      "Boil with sugar or honey until tender.",
      "Add milk and cinnamon, cook 5 more minutes.",
      "Serve warm or cold.",
    ],
  },
  {
    id: 15,
    title: "Eid Kahk",
    image: "dessert_kahk_eid",
    description:
      "Crispy cookies filled with dates or nuts, dusted with powdered sugar, traditional for Eid celebrations.",
    time: "60 min",
    difficulty: "Medium",
    servings: "10 people",
    ingredients: [
      "500 g flour",
      "250 g ghee",
      "1 cup sugar",
      "Filling: dates or nuts",
      "Powdered sugar for dusting",
    ],
    steps: [
      "Knead flour with ghee and sugar until dough forms.",
      "Roll out and cut into small circles.",
      "Add filling in the center and close.",
      "Bake until golden.",
      "Dust with powdered sugar after cooling.",
    ],
  },
 
];
