import { BaseRecipe } from "@/types/recipe.types";


export const DRINKS_AR: BaseRecipe[] = [
  {
    id: 1,
    title: "التمر الهندي",
    image: "drink_tamar_hindi",
    description:
      "مشروب بارد شعبي يُحضّر من التمر الهندي المنقوع والمصفّى، ويُحلى بالسكر. يُقدم بكثرة في رمضان والأعياد.",
    time: "30 دقيقة",
    difficulty: "سهل",
    servings: "6 أشخاص",
    ingredients: [
      "1 كوب تمر هندي مجفف",
      "4 أكواب ماء",
      "نصف كوب سكر (أو حسب الرغبة)",
      "مكعبات ثلج للتقديم",
    ],
    steps: [
      "انقع التمر الهندي في الماء لمدة ساعتين.",
      "صفِّ الخليط وأضف السكر.",
      "قلّب جيداً حتى يذوب السكر.",
      "قدمه بارداً مع الثلج.",
    ],
  },
  {
    id: 2,
    title: "الكركديه",
    image: "drink_karkadeh",
    description:
      "مشروب منعش من زهرة الكركديه، يُقدّم بارداً أو ساخناً ويتميز بلونه الأحمر الجميل وطعمه الحامض قليلًا.",
    time: "20 دقيقة",
    difficulty: "سهل",
    servings: "4 أشخاص",
    ingredients: [
      "1 كوب زهور كركديه مجففة",
      "4 أكواب ماء",
      "نصف كوب سكر",
      "مكعبات ثلج للتقديم (اختياري)",
    ],
    steps: [
      "اغسل زهور الكركديه وانقعها في الماء الساخن 10 دقائق.",
      "صفِّ المشروب وأضف السكر حسب الرغبة.",
      "قدمه بارداً أو ساخناً حسب الرغبة.",
    ],
  },
  {
    id: 3,
    title: "عرقسوس",
    image: "drink_arqsoos",
    description:
      "مشروب عشبي شعبي داكن اللون له طعم مميز ومنعش، يُقدّم بارداً خصوصاً في الصيف.",
    time: "25 دقيقة",
    difficulty: "سهل",
    servings: "4 أشخاص",
    ingredients: [
      "1 كوب عرقسوس مطحون",
      "4 أكواب ماء",
      "نصف كوب سكر",
      "مكعبات ثلج للتقديم",
    ],
    steps: [
      "اغلي الماء وأضف العرقسوس وحرك جيداً.",
      "اتركه يبرد قليلاً ثم صفّه.",
      "أضف السكر وقلّب جيداً.",
      "قدمه بارداً مع الثلج.",
    ],
  },
  {
    id: 4,
    title: "السوبيا",
    image: "drink_sobya",
    description:
      "مشروب شعبي مصري مصنوع من الأرز المخمر بالحليب، منعش ومغذي خصوصاً في رمضان.",
    time: "12 ساعة (تحضير + تخمير)",
    difficulty: "متوسط",
    servings: "6 أشخاص",
    ingredients: [
      "1 كوب أرز",
      "1 كوب حليب",
      "1 كوب سكر",
      "ماء حسب الحاجة",
      "مكسرات للتزيين (اختياري)",
    ],
    steps: [
      "انقع الأرز في الماء لعدة ساعات ثم اطحنه.",
      "امزج مع الحليب والسكر واتركه يتخمر طوال الليل.",
      "صفّ المشروب وقدمه بارداً.",
      "زيّنه بالمكسرات إذا رغبت.",
    ],
  },
  {
    id: 5,
    title: "عصير قصب السكر",
    image: "drink_sugarcane",
    description:
      "مشروب شعبي منعش مصنوع من عصير أعواد قصب السكر الطازجة، يُقدّم بارداً مع الثلج.",
    time: "15 دقيقة",
    difficulty: "سهل",
    servings: "4 أشخاص",
    ingredients: ["1 كغ قصب سكر مقطع", "مكعبات ثلج", "شرائح ليمون (اختياري)"],
    steps: [
      "اعصر أعواد قصب السكر للحصول على العصير الطازج.",
      "صب العصير في أكواب مع الثلج.",
      "أضف شرائح الليمون حسب الرغبة.",
      "قدمه بارداً.",
    ],
  },
  {
    id: 6,
    title: "عصير برتقال",
    image: "drink_orange_juice",
    description: "عصير برتقال طبيعي طازج، غني بالفيتامينات ويُقدّم بارداً.",
    time: "10 دقائق",
    difficulty: "سهل",
    servings: "4 أشخاص",
    ingredients: ["6 حبات برتقال طازج", "مكعبات ثلج للتقديم", "سكر حسب الرغبة"],
    steps: [
      "اعصر البرتقال للحصول على العصير الطازج.",
      "أضف السكر حسب الرغبة وحرك جيداً.",
      "قدمه بارداً مع الثلج.",
    ],
  },
  {
    id: 7,
    title: "عصير مانجو",
    image: "drink_mango_juice",
    description: "عصير مانجو طبيعي منعش، محبب للكبار والصغار.",
    time: "10 دقائق",
    difficulty: "سهل",
    servings: "4 أشخاص",
    ingredients: [
      "3 حبات مانجو ناضجة",
      "1 كوب ماء أو حسب الرغبة",
      "سكر حسب الرغبة",
      "مكعبات ثلج",
    ],
    steps: [
      "قشر وقطع المانجو.",
      "اخلطها في الخلاط مع الماء والسكر.",
      "صب العصير في أكواب وأضف الثلج.",
      "قدمه بارداً.",
    ],
  },
  {
    id: 8,
    title: "عصير فراولة",
    image: "drink_strawberry_juice",
    description: "عصير فراولة طازج ومنعش، مثالي للصيف.",
    time: "10 دقائق",
    difficulty: "سهل",
    servings: "4 أشخاص",
    ingredients: [
      "2 كوب فراولة طازجة",
      "1 كوب ماء أو حسب الرغبة",
      "سكر حسب الرغبة",
      "مكعبات ثلج",
    ],
    steps: [
      "نظف الفراولة وقطعها.",
      "اخلطها في الخلاط مع الماء والسكر.",
      "صب العصير في أكواب وأضف الثلج.",
      "قدمه بارداً.",
    ],
  },
  {
    id: 9,
    title: "شاي أحمر",
    image: "drink_black_tea",
    description: "الشاي الأحمر التقليدي المصري، يُقدّم ساخناً غالبًا مع السكر.",
    time: "10 دقائق",
    difficulty: "سهل",
    servings: "4 أشخاص",
    ingredients: ["4 أكواب ماء", "4 ملاعق صغيرة شاي أحمر", "سكر حسب الرغبة"],
    steps: [
      "اغلي الماء وأضف الشاي.",
      "اتركه يغلي لمدة 3-5 دقائق.",
      "صفه واسكبه في أكواب.",
      "أضف السكر حسب الرغبة.",
    ],
  },
];

export const DRINKS_EN: BaseRecipe[] = [
  {
    id: 1,
    title: "Tamarind Drink",
    image: "drink_tamar_hindi",
    description:
      "A popular cold drink made from soaked and strained tamarind, sweetened with sugar. Commonly served during Ramadan and holidays.",
    time: "30 minutes",
    difficulty: "Easy",
    servings: "6 servings",
    ingredients: [
      "1 cup dried tamarind",
      "4 cups water",
      "1/2 cup sugar (or to taste)",
      "Ice cubes for serving",
    ],
    steps: [
      "Soak the tamarind in water for 2 hours.",
      "Strain the mixture and add sugar.",
      "Stir well until sugar dissolves.",
      "Serve chilled with ice.",
    ],
  },
  {
    id: 2,
    title: "Hibiscus Drink",
    image: "drink_karkadeh",
    description:
      "A refreshing drink made from hibiscus flowers, served hot or cold with a slightly tart flavor and vibrant red color.",
    time: "20 minutes",
    difficulty: "Easy",
    servings: "4 servings",
    ingredients: [
      "1 cup dried hibiscus flowers",
      "4 cups water",
      "1/2 cup sugar",
      "Ice cubes (optional)",
    ],
    steps: [
      "Wash hibiscus flowers and steep in hot water for 10 minutes.",
      "Strain and add sugar to taste.",
      "Serve hot or cold as desired.",
    ],
  },
  {
    id: 3,
    title: "Licorice Drink",
    image: "drink_arqsoos",
    description:
      "A dark-colored herbal drink with a unique refreshing taste, popular in Egypt, especially served cold during summer.",
    time: "25 minutes",
    difficulty: "Easy",
    servings: "4 servings",
    ingredients: [
      "1 cup ground licorice root",
      "4 cups water",
      "1/2 cup sugar",
      "Ice cubes for serving",
    ],
    steps: [
      "Boil water and add licorice root, stir well.",
      "Let it cool slightly, then strain.",
      "Add sugar and stir until dissolved.",
      "Serve chilled with ice.",
    ],
  },
  {
    id: 4,
    title: "Sobya",
    image: "drink_sobya",
    description:
      "A traditional Egyptian drink made from fermented rice with milk, refreshing and nutritious, especially popular during Ramadan.",
    time: "12 hours (preparation + fermentation)",
    difficulty: "Medium",
    servings: "6 servings",
    ingredients: [
      "1 cup rice",
      "1 cup milk",
      "1 cup sugar",
      "Water as needed",
      "Nuts for garnish (optional)",
    ],
    steps: [
      "Soak rice for several hours and then grind it.",
      "Mix with milk and sugar and let it ferment overnight.",
      "Strain the drink and serve chilled.",
      "Garnish with nuts if desired.",
    ],
  },
  {
    id: 5,
    title: "Sugarcane Juice",
    image: "drink_sugarcane",
    description:
      "A refreshing drink made from freshly squeezed sugarcane, served cold with ice cubes.",
    time: "15 minutes",
    difficulty: "Easy",
    servings: "4 servings",
    ingredients: [
      "1 kg sugarcane, cut",
      "Ice cubes",
      "Lemon slices (optional)",
    ],
    steps: [
      "Extract juice from sugarcane stalks.",
      "Pour juice into glasses with ice.",
      "Add lemon slices if desired.",
      "Serve chilled.",
    ],
  },
  {
    id: 6,
    title: "Orange Juice",
    image: "drink_orange_juice",
    description: "Fresh natural orange juice, rich in vitamins, served cold.",
    time: "10 minutes",
    difficulty: "Easy",
    servings: "4 servings",
    ingredients: ["6 fresh oranges", "Ice cubes for serving", "Sugar to taste"],
    steps: [
      "Squeeze the oranges to extract fresh juice.",
      "Add sugar to taste and stir well.",
      "Serve chilled with ice.",
    ],
  },
  {
    id: 7,
    title: "Mango Juice",
    image: "drink_mango_juice",
    description:
      "Natural and refreshing mango juice, loved by both adults and children.",
    time: "10 minutes",
    difficulty: "Easy",
    servings: "4 servings",
    ingredients: [
      "3 ripe mangoes",
      "1 cup water or as needed",
      "Sugar to taste",
      "Ice cubes",
    ],
    steps: [
      "Peel and chop the mangoes.",
      "Blend with water and sugar.",
      "Pour into glasses and add ice.",
      "Serve chilled.",
    ],
  },
  {
    id: 8,
    title: "Strawberry Juice",
    image: "drink_strawberry_juice",
    description: "Fresh and refreshing strawberry juice, perfect for summer.",
    time: "10 minutes",
    difficulty: "Easy",
    servings: "4 servings",
    ingredients: [
      "2 cups fresh strawberries",
      "1 cup water or as needed",
      "Sugar to taste",
      "Ice cubes",
    ],
    steps: [
      "Clean and chop strawberries.",
      "Blend with water and sugar.",
      "Pour into glasses and add ice.",
      "Serve chilled.",
    ],
  },
  {
    id: 9,
    title: "Black Tea",
    image: "drink_black_tea",
    description:
      "Traditional Egyptian black tea, usually served hot with sugar.",
    time: "10 minutes",
    difficulty: "Easy",
    servings: "4 servings",
    ingredients: ["4 cups water", "4 tsp black tea", "Sugar to taste"],
    steps: [
      "Boil water and add tea leaves.",
      "Let boil 3-5 minutes.",
      "Strain and pour into cups.",
      "Add sugar to taste.",
    ],
  },
];
