import { BaseRecipe } from "@/types/recipe.types";

export const PHARAONIC_AR: BaseRecipe[] = [
  {
    id: 1,
    title: "عدس مسلوق",
    image: "pharaonic_lentils",
    description:
      "طبق نباتي بسيط اعتمد عليه الفراعنة كمصدر رئيسي للبروتين، يُطهى العدس مع الماء والملح ويُقدّم مع الخبز.",
    difficulty: "سهلة",
    servings: "٤ أشخاص",
    time: "٤٠ دقيقة",
    ingredients: ["٢ كوب عدس بني", "ماء كافٍ للسلق", "ملح حسب الرغبة"],
    steps: [
      "اغسل العدس جيدًا وصفيه.",
      "ضع العدس في قدر وأضف الماء.",
      "اتركه يغلي ثم خفف النار حتى ينضج.",
      "أضف الملح قبل التقديم مباشرة.",
    ],
  },
  {
    id: 2,
    title: "شوربة بصل وثوم",
    image: "pharaonic_onion_soup",
    description:
      "شوربة تقليدية عند الفراعنة، كانوا يعتبرون البصل والثوم مصدرًا للقوة والطاقة خاصة للعمال.",
    difficulty: "سهلة",
    servings: "٣ أشخاص",
    time: "٣٠ دقيقة",
    ingredients: ["٣ بصلات متوسطة", "٥ فصوص ثوم", "٤ أكواب ماء", "ملح وفلفل"],
    steps: [
      "قطّع البصل شرائح والثوم ناعمًا.",
      "ضع البصل والثوم في قدر مع القليل من الماء حتى يذبل.",
      "أضف باقي الماء واتركه يغلي.",
      "تبّل بالملح والفلفل وقدّم ساخنًا.",
    ],
  },
  {
    id: 3,
    title: "سلطة خيار وخس",
    image: "pharaonic_salad",
    description:
      "سلطة منعشة خفيفة من الخضروات الطازجة، كانت تقدم بجانب الخبز أو الأسماك المشوية.",
    difficulty: "سهلة",
    servings: "٤ أشخاص",
    time: "١٥ دقيقة",
    ingredients: [
      "٢ حبة خيار",
      "١ رأس خس صغير",
      "١ ملعقة كبيرة زيت زيتون",
      "عصير ليمونة",
      "رشة ملح",
    ],
    steps: [
      "اغسل الخيار والخس جيدًا.",
      "قطّع الخيار والخس إلى قطع متوسطة.",
      "اخلط المكونات مع الزيت وعصير الليمون.",
      "تبّل بالملح وقدّم مباشرة.",
    ],
  },
  {
    id: 4,
    title: "بط محشي بالقمح والعسل",
    image: "pharaonic_duck",
    description:
      "أكلة فاخرة عند الفراعنة، يُحشى البط بالقمح والعسل ثم يُشوى ليُقدّم في الولائم الملكية.",
    difficulty: "متوسطة",
    servings: "٦ أشخاص",
    time: "٩٠ دقيقة",
    ingredients: [
      "١ بطة كاملة منظفة",
      "١ كوب قمح مسلوق نصف سلقة",
      "٣ ملاعق كبيرة عسل",
      "ملح وفلفل",
    ],
    steps: [
      "اخلط القمح المسلوق مع العسل والملح والفلفل.",
      "احشُ البطة بالخليط وأغلقها جيدًا.",
      "ضعها في فرن متوسط الحرارة حتى تنضج تمامًا.",
      "قدّمها مع الخبز أو الخضار.",
    ],
  },
  {
    id: 5,
    title: "إوز مشوي",
    image: "pharaonic_goose",
    description:
      "كان الإوز من الطيور المفضلة لدى الفراعنة، يُتبل ويُشوى على النار أو في الأفران الطينية.",
    difficulty: "متوسطة",
    servings: "٥ أشخاص",
    time: "٨٠ دقيقة",
    ingredients: [
      "١ إوزة كاملة",
      "٣ ملاعق كبيرة زيت",
      "ملح وفلفل",
      "بصل للتتبيل",
    ],
    steps: [
      "نظّف الإوزة جيدًا.",
      "تُتبّل بالملح والفلفل والبصل.",
      "توضع في الفرن حتى تتحمر وتنضج.",
      "تُقدّم ساخنة بجانب الخبز أو الخضار.",
    ],
  },
  {
    id: 6,
    title: "حمام محشي بالعدس أو القمح",
    image: "pharaonic_pigeon",
    description:
      "الحمام المحشي كان طعامًا فاخرًا عند المصريين القدماء، يُحشى بالعدس أو القمح ويُطهى على النار.",
    difficulty: "متوسطة",
    servings: "٤ أشخاص",
    time: "٧٠ دقيقة",
    ingredients: [
      "٤ حمامات منظفة",
      "١ كوب عدس أو قمح مسلوق",
      "ملح وفلفل",
      "١ بصلة صغيرة مفرومة",
    ],
    steps: [
      "اخلط العدس أو القمح مع البصل والملح والفلفل.",
      "احشُ الحمام بالخليط وأغلقه جيدًا.",
      "اسلق الحمام نصف سلقة ثم حمره في الفرن.",
      "قدّمه مع الخبز.",
    ],
  },
  {
    id: 7,
    title: "لحم غزال مشوي",
    image: "pharaonic_deer",
    description:
      "كان لحم الغزال يُعتبر طعام الملوك والأغنياء في مصر القديمة، يُشوى على النار بتتبيلة بسيطة.",
    difficulty: "متقدمة",
    servings: "٤ أشخاص",
    time: "٦٠ دقيقة",
    ingredients: [
      "١ كغ لحم غزال",
      "٣ ملاعق زيت زيتون",
      "ملح وفلفل",
      "أعشاب برية للتتبيل (اختياري)",
    ],
    steps: [
      "قطّع اللحم إلى شرائح وتبّله بالزيت والملح والفلفل.",
      "اتركه يتشرب التتبيلة ٣٠ دقيقة.",
      "اشوه على النار حتى ينضج.",
      "قدّمه مع الخبز أو السلطة.",
    ],
  },
  {
    id: 8,
    title: "سمك مشوي على النار",
    image: "pharaonic_grilled_fish",
    description:
      "من أكثر الأطباق شيوعًا عند الفراعنة، يُشوى السمك الطازج من النيل مباشرة على الجمر.",
    difficulty: "سهلة",
    servings: "٣ أشخاص",
    time: "٣٠ دقيقة",
    ingredients: [
      "٣ أسماك متوسطة الحجم",
      "٢ ملعقة زيت زيتون",
      "ملح وفلفل",
      "عصير ليمون",
    ],
    steps: [
      "نظّف الأسماك جيدًا.",
      "تبّلها بالملح والزيت وعصير الليمون.",
      "اشوها على الجمر حتى تنضج.",
      "قدّمها ساخنة مع الخبز.",
    ],
  },
  {
    id: 9,
    title: "سمك مجفف (مملح)",
    image: "pharaonic_dried_fish",
    description:
      "كانوا يجففون السمك من النيل بالملح والشمس لحفظه لفترات طويلة، خاصة في أوقات الفيضانات.",
    difficulty: "سهلة",
    servings: "٥ أشخاص",
    time: "٣ أيام (للتجفيف)",
    ingredients: ["٥ أسماك متوسطة", "ملح خشن"],
    steps: [
      "نظّف الأسماك جيدًا.",
      "غطها بالملح واتركها في مكان مشمس.",
      "اتركها ٣ أيام حتى تجف تمامًا.",
      "تُؤكل مباشرة أو تُطهى لاحقًا.",
    ],
  },
  {
    id: 10,
    title: "يخنة سمك بالبصل",
    image: "pharaonic_fish_stew",
    description:
      "طبق دافئ من السمك المطبوخ مع البصل، كان شائعًا بين العامة لسهولة تحضيره وتكلفته القليلة.",
    difficulty: "سهلة",
    servings: "٤ أشخاص",
    time: "٤٥ دقيقة",
    ingredients: ["٤ قطع سمك", "٢ بصلة كبيرة", "٣ أكواب ماء", "ملح وفلفل"],
    steps: [
      "قطّع البصل شرائح وقلِّه قليلًا.",
      "أضف الماء والسمك ودع الخليط يغلي.",
      "تبّل بالملح والفلفل.",
      "اتركه على نار هادئة حتى ينضج السمك.",
    ],
  },
];

export const PHARAONIC_EN: BaseRecipe[] = [
  {
    id: 1,
    title: "Boiled Lentils",
    image: "pharaonic_lentils",
    description:
      "A simple vegetarian dish that the Pharaohs relied on as a main source of protein, cooked with water and salt and served with bread.",
    difficulty: "Easy",
    servings: "4 people",
    time: "40 minutes",
    ingredients: [
      "2 cups brown lentils",
      "Enough water for boiling",
      "Salt to taste",
    ],
    steps: [
      "Wash the lentils well and drain.",
      "Place the lentils in a pot and add water.",
      "Bring to a boil, then simmer until fully cooked.",
      "Add salt before serving.",
    ],
  },
  {
    id: 2,
    title: "Onion and Garlic Soup",
    image: "pharaonic_onion_soup",
    description:
      "A traditional soup for the Pharaohs, onion and garlic were considered sources of strength and energy, especially for workers.",
    difficulty: "Easy",
    servings: "3 people",
    time: "30 minutes",
    ingredients: [
      "3 medium onions",
      "5 garlic cloves",
      "4 cups water",
      "Salt and pepper",
    ],
    steps: [
      "Slice the onions and chop the garlic.",
      "Cook them in a pot with a little water until softened.",
      "Add the rest of the water and bring to a boil.",
      "Season with salt and pepper, and serve hot.",
    ],
  },
  {
    id: 3,
    title: "Cucumber and Lettuce Salad",
    image: "pharaonic_salad",
    description:
      "A refreshing salad of fresh vegetables, commonly served alongside bread or grilled fish.",
    difficulty: "Easy",
    servings: "4 people",
    time: "15 minutes",
    ingredients: [
      "2 cucumbers",
      "1 small head of lettuce",
      "1 tbsp olive oil",
      "Juice of 1 lemon",
      "Pinch of salt",
    ],
    steps: [
      "Wash the cucumbers and lettuce well.",
      "Chop into medium pieces.",
      "Mix with olive oil and lemon juice.",
      "Season with salt and serve immediately.",
    ],
  },
  {
    id: 4,
    title: "Duck Stuffed with Wheat and Honey",
    image: "pharaonic_duck",
    description:
      "A luxurious dish for the Pharaohs, duck stuffed with wheat and honey, then roasted for royal feasts.",
    difficulty: "Medium",
    servings: "6 people",
    time: "90 minutes",
    ingredients: [
      "1 whole duck, cleaned",
      "1 cup wheat, half-cooked",
      "3 tbsp honey",
      "Salt and pepper",
    ],
    steps: [
      "Mix the wheat with honey, salt, and pepper.",
      "Stuff the duck with the mixture and seal it well.",
      "Roast in a medium oven until fully cooked.",
      "Serve with bread or vegetables.",
    ],
  },
  {
    id: 5,
    title: "Roasted Goose",
    image: "pharaonic_goose",
    description:
      "Goose was one of the Pharaohs’ favorite birds, seasoned and roasted over fire or in clay ovens.",
    difficulty: "Medium",
    servings: "5 people",
    time: "80 minutes",
    ingredients: [
      "1 whole goose",
      "3 tbsp oil",
      "Salt and pepper",
      "1 onion for seasoning",
    ],
    steps: [
      "Clean the goose well.",
      "Season with salt, pepper, and onion.",
      "Roast in the oven until golden and cooked through.",
      "Serve hot with bread or vegetables.",
    ],
  },
  {
    id: 6,
    title: "Pigeon Stuffed with Lentils or Wheat",
    image: "pharaonic_pigeon",
    description:
      "Stuffed pigeon was a delicacy in ancient Egypt, filled with lentils or wheat and cooked over fire.",
    difficulty: "Medium",
    servings: "4 people",
    time: "70 minutes",
    ingredients: [
      "4 cleaned pigeons",
      "1 cup lentils or half-cooked wheat",
      "Salt and pepper",
      "1 small chopped onion",
    ],
    steps: [
      "Mix lentils or wheat with onion, salt, and pepper.",
      "Stuff the pigeons and seal them well.",
      "Boil them halfway, then roast in the oven.",
      "Serve with bread.",
    ],
  },
  {
    id: 7,
    title: "Grilled Venison",
    image: "pharaonic_deer",
    description:
      "Venison was considered food for kings and nobles in ancient Egypt, grilled with a simple seasoning.",
    difficulty: "Advanced",
    servings: "4 people",
    time: "60 minutes",
    ingredients: [
      "1 kg venison",
      "3 tbsp olive oil",
      "Salt and pepper",
      "Wild herbs for seasoning (optional)",
    ],
    steps: [
      "Cut the meat into slices and season with oil, salt, and pepper.",
      "Let it marinate for 30 minutes.",
      "Grill over fire until cooked through.",
      "Serve with bread or salad.",
    ],
  },
  {
    id: 8,
    title: "Grilled Fish over Fire",
    image: "pharaonic_grilled_fish",
    description:
      "One of the most common dishes of the Pharaohs, fresh Nile fish grilled directly over embers.",
    difficulty: "Easy",
    servings: "3 people",
    time: "30 minutes",
    ingredients: [
      "3 medium fish",
      "2 tbsp olive oil",
      "Salt and pepper",
      "Juice of 1 lemon",
    ],
    steps: [
      "Clean the fish well.",
      "Season with salt, oil, and lemon juice.",
      "Grill over embers until cooked.",
      "Serve hot with bread.",
    ],
  },
  {
    id: 9,
    title: "Dried (Salted) Fish",
    image: "pharaonic_dried_fish",
    description:
      "The Pharaohs preserved Nile fish by salting and sun-drying it, especially for times of flooding.",
    difficulty: "Easy",
    servings: "5 people",
    time: "3 days (drying)",
    ingredients: ["5 medium fish", "Coarse salt"],
    steps: [
      "Clean the fish well.",
      "Cover with salt and leave in the sun.",
      "Let it dry completely for 3 days.",
      "Eat directly or cook later.",
    ],
  },
  {
    id: 10,
    title: "Fish Stew with Onions",
    image: "pharaonic_fish_stew",
    description:
      "A warm dish of fish cooked with onions, popular among commoners for its simplicity and low cost.",
    difficulty: "Easy",
    servings: "4 people",
    time: "45 minutes",
    ingredients: [
      "4 pieces of fish",
      "2 large onions",
      "3 cups water",
      "Salt and pepper",
    ],
    steps: [
      "Slice the onions and sauté lightly.",
      "Add water and fish, then bring to a boil.",
      "Season with salt and pepper.",
      "Simmer until the fish is fully cooked.",
    ],
  },
];
