import { BaseRecipe } from "@/types/recipe.types";

export const RECIPES_AR: BaseRecipe[] = [
  {
    id: 1,
    title: "الكشري",
    image: "egyptian_koshari",
    description:
      "أشهر أكلة مصرية شعبية مكونة من عدس وأرز ومكرونة وصوص طماطم وبصل مقلي.",
    difficulty: "متوسطة",
    servings: "٤ أشخاص",
    time: "٥٠ دقيقة",
    ingredients: [
      "٢ كوب أرز",
      "١ كوب عدس بني",
      "١ كوب مكرونة",
      "٢ بصلة كبيرة",
      "صلصة طماطم",
      "بهارات (كمون، ملح، فلفل)",
    ],
    steps: [
      "اسلق المكرونة والعدس كل على حدة.",
      "اطبخ الأرز مع الكمون والملح.",
      "حضّر صلصة الطماطم بالثوم والخل.",
      "اقلي البصل حتى يصبح مقرمش.",
      "قدّم الأرز والعدس والمكرونة مع الصلصة والبصل على الوجه.",
    ],
  },
  {
    id: 2,
    title: "الملوخية",
    image: "egyptian_molokhia",
    description:
      "شوربة خضراء شهيرة في مصر تُطهى بأوراق الملوخية المفرومة مع الثوم والكزبرة، وتقدّم بجانب الأرز أو العيش.",
    difficulty: "سهلة",
    servings: "٤ أشخاص",
    time: "٣٠ دقيقة",
    ingredients: [
      "٥٠٠غ ملوخية مفرومة",
      "٥ فصوص ثوم",
      "٢ ملعقة كزبرة ناشفة",
      "مرق دجاج أو لحم",
    ],
    steps: [
      "سخّن المرق حتى الغليان.",
      "أضف الملوخية المفرومة مع التحريك السريع.",
      "في مقلاة: اقلي الثوم مع الكزبرة.",
      "أضف التقلية إلى الملوخية واغلق النار فورًا.",
      "قدّمها مع الأرز الأبيض أو الخبز.",
    ],
  },
  {
    id: 3,
    title: "الفتة",
    image: "egyptian_fatta",
    description:
      "طبق تقليدي مصري يتكون من طبقات عيش محمص، أرز، ولحمة، يُزين بصلصة الطماطم والثوم.",
    difficulty: "متوسطة",
    servings: "٥ أشخاص",
    time: "٦٠ دقيقة",
    ingredients: [
      "٢ كوب أرز",
      "عيش بلدي محمص",
      "لحم مسلوق",
      "صلصة طماطم بالثوم",
      "خل",
    ],
    steps: [
      "اسلق اللحم واحتفظ بالمرق.",
      "حمّص العيش وقطّعه مكعبات.",
      "اطبخ الأرز بالمرق.",
      "رتب العيش ثم الأرز ثم اللحم.",
      "اسكب صلصة الطماطم والثوم فوق الوجه.",
    ],
  },
  {
    id: 4,
    title: "طاجن بامية",
    image: "egyptian_okra",
    description:
      "بامية مطبوخة مع صلصة الطماطم واللحم، تُطهى في طاجن فخاري لتعطي نكهة مميزة.",
    difficulty: "متوسطة",
    servings: "٤ أشخاص",
    time: "٦٠ دقيقة",
    ingredients: [
      "٥٠٠ غرام بامية",
      "٣٠٠ غرام لحم مكعبات",
      "٢ كوب طماطم معصورة",
      "بصل وثوم",
      "ملح وفلفل",
    ],
    steps: [
      "قلّي البصل والثوم مع اللحم حتى يتحمر.",
      "أضف الطماطم واتركها تغلي.",
      "أضف البامية واتركها حتى تنضج.",
      "انقل الخليط إلى طاجن وأدخله الفرن.",
    ],
  },
  {
    id: 5,
    title: "طاجن مسقعة (باذنجان)",
    image: "egyptian_moussaka",
    description:
      "باذنجان مقلي مع صلصة الطماطم والفلفل، يُطهى في طاجن بالفرن.",
    difficulty: "سهلة",
    servings: "٤ أشخاص",
    time: "٥٠ دقيقة",
    ingredients: [
      "٢ باذنجان كبير مقطع ومقلي",
      "٢ كوب طماطم معصورة",
      "٢ فلفل أخضر",
      "بصلة مفرومة",
      "ملح وفلفل",
    ],
    steps: [
      "اقلي الباذنجان والفلفل.",
      "حمّر البصل وأضف الطماطم.",
      "ضع الباذنجان والفلفل في الطاجن.",
      "أضف الصلصة وأدخله الفرن حتى يتماسك.",
    ],
  },
  {
    id: 6,
    title: "المحشي",
    image: "egyptian_mahshi",
    description:
      "خضروات مثل الكرنب وورق العنب والكوسة محشية بالأرز والبهارات وصلصة الطماطم.",
    difficulty: "متقدمة",
    servings: "٦ أشخاص",
    time: "١٢٠ دقيقة",
    ingredients: [
      "ورق عنب/كرنب/كوسة",
      "٢ كوب أرز",
      "١ كوب طماطم معصورة",
      "بصلة مفرومة",
      "شبت وبقدونس",
    ],
    steps: [
      "اخلط الأرز مع الطماطم والبصل والأعشاب.",
      "احشِ الخضار بالخليط.",
      "رتبها في قدر مع شرائح بطاطس أسفلها.",
      "اسكب المرق واطبخ على نار هادئة.",
    ],
  },
  {
    id: 7,
    title: "الفاصوليا البيضاء بالصلصة",
    image: "egyptian_beans",
    description:
      "طبق منزلي بسيط من الفاصوليا البيضاء المطبوخة مع صلصة الطماطم والثوم.",
    difficulty: "سهلة",
    servings: "٤ أشخاص",
    time: "٥٥ دقيقة",
    ingredients: [
      "٢ كوب فاصوليا بيضاء منقوعة",
      "٢ كوب طماطم معصورة",
      "٤ فصوص ثوم",
      "ملح وفلفل",
    ],
    steps: [
      "اسلق الفاصوليا حتى تنضج.",
      "حضّر صلصة الطماطم مع الثوم.",
      "أضف الفاصوليا إلى الصلصة واتركها تغلي.",
      "قدّمها ساخنة مع الأرز.",
    ],
  },
  {
    id: 8,
    title: "البطاطس بالصلصة",
    image: "egyptian_potato_stew",
    description:
      "بطاطس مطبوخة بصلصة الطماطم والثوم، وجبة شعبية لذيذة وسهلة.",
    difficulty: "سهلة",
    servings: "٤ أشخاص",
    time: "٤٥ دقيقة",
    ingredients: [
      "٤ حبات بطاطس مقطعة مكعبات",
      "٢ كوب طماطم معصورة",
      "٣ فصوص ثوم",
      "ملح وفلفل",
    ],
    steps: [
      "قلّي الثوم حتى يذهب لونه.",
      "أضف الطماطم والبطاطس.",
      "اتركها على نار هادئة حتى تنضج البطاطس.",
      "قدّمها مع الأرز أو الخبز.",
    ],
  },
  {
    id: 9,
    title: "سمك مقلي أو مشوي (بلطي/بوري)",
    image: "egyptian_fish",
    description:
      "أشهر الأطباق البحرية في مصر، يُطهى السمك البلطي أو البوري مقليًا أو مشويًا على الجمر.",
    difficulty: "سهلة",
    servings: "٣ أشخاص",
    time: "٤٠ دقيقة",
    ingredients: [
      "٣ سمكات (بلطي أو بوري)",
      "ملح وفلفل",
      "زيت للقلي أو للشوي",
      "عصير ليمون",
    ],
    steps: [
      "نظّف السمك جيدًا.",
      "تبّله بالملح والفلفل والليمون.",
      "اقليه في الزيت أو اشوه على الجمر.",
      "قدّمه مع أرز صيادية أو سلطة.",
    ],
  },
  {
    id: 10,
    title: "جمبري مشوي",
    image: "egyptian_shrimp",
    description:
      "جمبري متبّل بالليمون والثوم يُشوى ليقدّم كطبق بحري مميز.",
    difficulty: "سهلة",
    servings: "٤ أشخاص",
    time: "٣٠ دقيقة",
    ingredients: [
      "٥٠٠ غرام جمبري",
      "٤ فصوص ثوم",
      "عصير ليمون",
      "ملح وفلفل",
    ],
    steps: [
      "تبّل الجمبري بالثوم والليمون والملح.",
      "اتركه ٢٠ دقيقة ليتشرب التتبيلة.",
      "اشوه على الفحم أو في الفرن.",
      "قدّمه ساخنًا.",
    ],
  },
  {
    id: 11,
    title: "طاجن سي فود",
    image: "egyptian_seafood_tagen",
    description:
      "طاجن يحتوي على خليط من الأسماك والجمبري والكاليماري مطبوخ مع صلصة الطماطم في الفرن.",
    difficulty: "متوسطة",
    servings: "٥ أشخاص",
    time: "٦٠ دقيقة",
    ingredients: [
      "٥٠٠ غرام سي فود مشكل",
      "٢ كوب طماطم معصورة",
      "بصل وثوم",
      "ملح وفلفل",
    ],
    steps: [
      "قلّي البصل والثوم مع صلصة الطماطم.",
      "أضف السي فود واخلط جيدًا.",
      "انقل الخليط إلى طاجن وأدخله الفرن.",
      "قدّم ساخنًا مع الأرز.",
    ],
  },
  {
    id: 12,
    title: "بط محشي",
    image: "egyptian_duck",
    description:
      "بطة محشية بالأرز والتوابل تُطهى في الفرن وتقدّم في المناسبات.",
    difficulty: "متقدمة",
    servings: "٦ أشخاص",
    time: "١٢٠ دقيقة",
    ingredients: [
      "١ بطة كاملة",
      "٢ كوب أرز",
      "بصل مفروم",
      "توابل (قرفة، فلفل، ملح)",
    ],
    steps: [
      "اخلط الأرز مع البصل والتوابل.",
      "احشُ البطة بالخليط.",
      "ادهنها بالسمن وأدخلها الفرن حتى تنضج.",
      "قدّمها مع الأرز والسلطات.",
    ],
  },
  {
    id: 13,
    title: "حمام محشي",
    image: "egyptian_pigeon",
    description:
      "حمام محشي بالأرز أو الفريك، من الأطباق المصرية التراثية الشهيرة.",
    difficulty: "متوسطة",
    servings: "٤ أشخاص",
    time: "٧٠ دقيقة",
    ingredients: [
      "٤ حمامات",
      "١ كوب فريك أو أرز",
      "بصلة مفرومة",
      "ملح وفلفل",
    ],
    steps: [
      "اخلط الفريك أو الأرز مع البصل والملح والفلفل.",
      "احشُ الحمام وأغلقه جيدًا.",
      "اسلقه نصف سلقة ثم حمّره.",
      "قدّمه مع الخبز أو الأرز.",
    ],
  },
  {
    id: 14,
    title: "كفتة مشوية",
    image: "egyptian_kofta",
    description:
      "كفتة من اللحم المفروم مع البصل والتوابل تُشكّل على أسياخ وتشوى.",
    difficulty: "سهلة",
    servings: "٥ أشخاص",
    time: "٥٠ دقيقة",
    ingredients: [
      "٥٠٠ غرام لحم مفروم",
      "١ بصلة مبشورة",
      "ملح وفلفل وبهارات",
      "بقدونس مفروم",
    ],
    steps: [
      "اخلط اللحم مع البصل والتوابل والبقدونس.",
      "شكّل الكفتة على أسياخ.",
      "اشوها على الفحم حتى تنضج.",
      "قدّمها مع العيش البلدي والطحينة.",
    ],
  },
  {
    id: 15,
    title: "كباب",
    image: "egyptian_kebab",
    description:
      "قطع لحم متبلة تُشوى على الفحم وتقدّم مع السلطات والعيش.",
    difficulty: "متوسطة",
    servings: "٥ أشخاص",
    time: "٦٠ دقيقة",
    ingredients: [
      "١ كغ لحم مكعبات",
      "بصل مبشور",
      "ملح وفلفل",
      "عصير ليمون",
    ],
    steps: [
      "تبّل اللحم بالبصل والملح والفلفل والليمون.",
      "اتركه ليتبل ٣ ساعات على الأقل.",
      "شكّل القطع على أسياخ واشوها على الفحم.",
      "قدّمها ساخنة مع السلطة.",
    ],
  },
  {
    id: 16,
    title: "فراخ مشوية",
    image: "egyptian_chicken",
    description:
      "فراخ متبلة بالأعشاب والبهارات، تُشوى في الفرن أو على الفحم.",
    difficulty: "سهلة",
    servings: "٤ أشخاص",
    time: "٦٠ دقيقة",
    ingredients: [
      "١ دجاجة كاملة",
      "ثوم مهروس",
      "عصير ليمون",
      "ملح وفلفل",
    ],
    steps: [
      "تبّل الدجاج بالثوم والليمون والملح والفلفل.",
      "اتركه ساعة في التتبيلة.",
      "اشوه في الفرن أو على الفحم حتى ينضج.",
      "قدّمه مع الأرز أو البطاطس.",
    ],
  },
];



export const RECIPES_EN: BaseRecipe[] = [
  {
    id: 1,
    title: "Koshari",
    image: "egyptian_koshari",
    description:
      "Egypt's most famous street food, a mix of lentils, rice, pasta, tomato sauce, and fried onions.",
    difficulty: "Medium",
    servings: "4 people",
    time: "50 minutes",
    ingredients: [
      "2 cups rice",
      "1 cup brown lentils",
      "1 cup pasta",
      "2 large onions",
      "Tomato sauce",
      "Spices (cumin, salt, pepper)",
    ],
    steps: [
      "Boil the pasta and lentils separately.",
      "Cook the rice with cumin and salt.",
      "Prepare tomato sauce with garlic and vinegar.",
      "Fry the onions until crispy.",
      "Serve rice, lentils, and pasta with sauce and onions on top.",
    ],
  },
  {
    id: 2,
    title: "Molokhia",
    image: "egyptian_molokhia",
    description:
      "A famous Egyptian green soup made from finely chopped jute leaves, cooked with garlic and coriander, served with rice or bread.",
    difficulty: "Easy",
    servings: "4 people",
    time: "30 minutes",
    ingredients: [
      "500g chopped molokhia leaves",
      "5 garlic cloves",
      "2 tbsp dried coriander",
      "Chicken or beef broth",
    ],
    steps: [
      "Heat the broth until boiling.",
      "Add the chopped molokhia and stir quickly.",
      "In a pan, sauté garlic with coriander.",
      "Add the sautéed mixture to the molokhia and remove from heat immediately.",
      "Serve with white rice or bread.",
    ],
  },
  {
    id: 3,
    title: "Fatta",
    image: "egyptian_fatta",
    description:
      "Traditional Egyptian dish made with layers of toasted bread, rice, and meat, topped with tomato-garlic sauce.",
    difficulty: "Medium",
    servings: "5 people",
    time: "60 minutes",
    ingredients: [
      "2 cups rice",
      "Toasted Egyptian bread",
      "Cooked meat",
      "Tomato sauce with garlic",
      "Vinegar",
    ],
    steps: [
      "Boil the meat and keep the broth.",
      "Toast the bread and cut into cubes.",
      "Cook rice with the broth.",
      "Layer the bread, then rice, then meat.",
      "Pour tomato-garlic sauce on top before serving.",
    ],
  },
  {
    id: 4,
    title: "Okra Tagine",
    image: "egyptian_okra",
    description:
      "Okra cooked with tomato sauce and meat, baked in a clay pot for a unique flavor.",
    difficulty: "Medium",
    servings: "4 people",
    time: "60 minutes",
    ingredients: [
      "500g okra",
      "300g meat cubes",
      "2 cups crushed tomatoes",
      "Onion and garlic",
      "Salt and pepper",
    ],
    steps: [
      "Sauté onion and garlic with meat until browned.",
      "Add tomatoes and let it boil.",
      "Add okra and cook until tender.",
      "Transfer to a tagine and bake in the oven.",
    ],
  },
  {
    id: 5,
    title: "Moussaka Tagine (Eggplant)",
    image: "egyptian_moussaka",
    description:
      "Fried eggplant with tomato sauce and peppers, baked in a tagine in the oven.",
    difficulty: "Easy",
    servings: "4 people",
    time: "50 minutes",
    ingredients: [
      "2 large eggplants, sliced and fried",
      "2 cups crushed tomatoes",
      "2 green peppers",
      "Chopped onion",
      "Salt and pepper",
    ],
    steps: [
      "Fry the eggplants and peppers.",
      "Sauté onions and add tomatoes.",
      "Place eggplants and peppers in the tagine.",
      "Add sauce and bake until set.",
    ],
  },
  {
    id: 6,
    title: "Mahshi (Stuffed Vegetables)",
    image: "egyptian_mahshi",
    description:
      "Vegetables like cabbage, grape leaves, or zucchini stuffed with rice, herbs, and tomato sauce.",
    difficulty: "Advanced",
    servings: "6 people",
    time: "120 minutes",
    ingredients: [
      "Grape leaves/Cabbage/Zucchini",
      "2 cups rice",
      "1 cup crushed tomatoes",
      "Chopped onion",
      "Dill and parsley",
    ],
    steps: [
      "Mix rice with tomatoes, onion, and herbs.",
      "Stuff the vegetables with the mixture.",
      "Arrange in a pot with potato slices at the bottom.",
      "Pour broth and cook on low heat until done.",
    ],
  },
  {
    id: 7,
    title: "White Beans in Tomato Sauce",
    image: "egyptian_beans",
    description:
      "Simple home-cooked dish of white beans simmered in tomato sauce with garlic.",
    difficulty: "Easy",
    servings: "4 people",
    time: "55 minutes",
    ingredients: [
      "2 cups soaked white beans",
      "2 cups crushed tomatoes",
      "4 garlic cloves",
      "Salt and pepper",
    ],
    steps: [
      "Boil beans until tender.",
      "Prepare tomato sauce with garlic.",
      "Add beans to sauce and simmer.",
      "Serve hot with rice.",
    ],
  },
  {
    id: 8,
    title: "Potatoes in Tomato Sauce",
    image: "egyptian_potato_stew",
    description:
      "Potatoes cooked in tomato sauce with garlic, a simple and popular side dish.",
    difficulty: "Easy",
    servings: "4 people",
    time: "45 minutes",
    ingredients: [
      "4 potatoes, cubed",
      "2 cups crushed tomatoes",
      "3 garlic cloves",
      "Salt and pepper",
    ],
    steps: [
      "Sauté garlic until golden.",
      "Add tomatoes and potatoes.",
      "Simmer on low heat until potatoes are tender.",
      "Serve with rice or bread.",
    ],
  },
  {
    id: 9,
    title: "Fried or Grilled Fish (Tilapia/Bouri)",
    image: "egyptian_fish",
    description:
      "Popular Egyptian fish dish, either fried or grilled over charcoal.",
    difficulty: "Easy",
    servings: "3 people",
    time: "40 minutes",
    ingredients: [
      "3 fish (tilapia or bouri)",
      "Salt and pepper",
      "Oil for frying or grilling",
      "Lemon juice",
    ],
    steps: [
      "Clean the fish thoroughly.",
      "Season with salt, pepper, and lemon juice.",
      "Fry in oil or grill over charcoal.",
      "Serve with Sayadiya rice or salad.",
    ],
  },
  {
    id: 10,
    title: "Grilled Shrimp",
    image: "egyptian_shrimp",
    description:
      "Shrimp marinated with lemon and garlic, grilled to perfection.",
    difficulty: "Easy",
    servings: "4 people",
    time: "30 minutes",
    ingredients: [
      "500g shrimp",
      "4 garlic cloves",
      "Lemon juice",
      "Salt and pepper",
    ],
    steps: [
      "Marinate shrimp with garlic, lemon, salt, and pepper.",
      "Leave for 20 minutes to absorb flavors.",
      "Grill on charcoal or in the oven.",
      "Serve hot.",
    ],
  },
  {
    id: 11,
    title: "Seafood Tagine",
    image: "egyptian_seafood_tagen",
    description:
      "Tagine with mixed seafood (fish, shrimp, calamari) cooked in tomato sauce.",
    difficulty: "Medium",
    servings: "5 people",
    time: "60 minutes",
    ingredients: [
      "500g mixed seafood",
      "2 cups crushed tomatoes",
      "Onion and garlic",
      "Salt and pepper",
    ],
    steps: [
      "Sauté onion and garlic with tomato sauce.",
      "Add seafood and mix well.",
      "Transfer to tagine and bake in the oven.",
      "Serve hot with rice.",
    ],
  },
  {
    id: 12,
    title: "Stuffed Duck",
    image: "egyptian_duck",
    description:
      "Duck stuffed with rice and spices, baked in the oven, ideal for special occasions.",
    difficulty: "Advanced",
    servings: "6 people",
    time: "120 minutes",
    ingredients: [
      "1 whole duck",
      "2 cups rice",
      "Chopped onion",
      "Spices (cinnamon, pepper, salt)",
    ],
    steps: [
      "Mix rice with onion and spices.",
      "Stuff the duck with the mixture.",
      "Brush with butter and bake until cooked.",
      "Serve with rice and salads.",
    ],
  },
  {
    id: 13,
    title: "Stuffed Pigeon",
    image: "egyptian_pigeon",
    description:
      "Pigeon stuffed with rice or freekeh, a traditional Egyptian delicacy.",
    difficulty: "Medium",
    servings: "4 people",
    time: "70 minutes",
    ingredients: [
      "4 pigeons",
      "1 cup freekeh or rice",
      "Chopped onion",
      "Salt and pepper",
    ],
    steps: [
      "Mix freekeh or rice with onion, salt, and pepper.",
      "Stuff the pigeons and close properly.",
      "Partially boil then brown in oven or pan.",
      "Serve with bread or rice.",
    ],
  },
  {
    id: 14,
    title: "Grilled Kofta",
    image: "egyptian_kofta",
    description:
      "Minced meat mixed with onion and spices, shaped onto skewers and grilled.",
    difficulty: "Easy",
    servings: "5 people",
    time: "50 minutes",
    ingredients: [
      "500g minced meat",
      "1 grated onion",
      "Salt, pepper, spices",
      "Chopped parsley",
    ],
    steps: [
      "Mix meat with onion, spices, and parsley.",
      "Shape onto skewers.",
      "Grill over charcoal until cooked.",
      "Serve with Egyptian bread and tahini.",
    ],
  },
  {
    id: 15,
    title: "Kebab",
    image: "egyptian_kebab",
    description:
      "Marinated meat cubes grilled on skewers, served with salad and bread.",
    difficulty: "Medium",
    servings: "5 people",
    time: "60 minutes",
    ingredients: [
      "1 kg meat cubes",
      "Grated onion",
      "Salt and pepper",
      "Lemon juice",
    ],
    steps: [
      "Season meat with onion, salt, pepper, and lemon juice.",
      "Let it marinate for at least 3 hours.",
      "Skewer and grill over charcoal.",
      "Serve hot with salad.",
    ],
  },
  {
    id: 16,
    title: "Grilled Chicken",
    image: "egyptian_chicken",
    description:
      "Whole chicken marinated with herbs and spices, roasted in oven or grilled.",
    difficulty: "Easy",
    servings: "4 people",
    time: "60 minutes",
    ingredients: [
      "1 whole chicken",
      "Crushed garlic",
      "Lemon juice",
      "Salt and pepper",
    ],
    steps: [
      "Marinate chicken with garlic, lemon, salt, and pepper.",
      "Leave for 1 hour.",
      "Grill in oven or over charcoal until cooked.",
      "Serve with rice or potatoes.",
    ],
  },
];
