import { BaseRecipe } from "@/types/recipe.types";

export const RECIPES_AR: BaseRecipe[] = [
  {
    id: 1,
    title: "المقلوبة",
    image: "recipe_maqluba",
    description:
      "طبق فلسطيني تقليدي يجمع بين الأرز والباذنجان المقلي والبطاطا مع اللحم أو الدجاج. يُقلب عند التقديم ليكشف عن طبق غني بالنكهات الأصيلة ويُقدم غالبًا في الولائم والمناسبات العائلية.",
    difficulty: "متوسطة",
    servings: "٤ أشخاص",
    time: "٤٥ دقيقة",
    ingredients: [
      "٢ كوب أرز",
      "١ كيلو دجاج أو لحم",
      "٢ حبة باذنجان مقلي",
      "حبة بطاطا مقلية",
      "بهارات مشكلة، ملح، فلفل",
    ],
    steps: [
      "اسلقي اللحم أو الدجاج مع البهارات حتى ينضج.",
      "انقع الأرز نصف ساعة ثم صفيه.",
      "ضعي الباذنجان والبطاطا في قاع الطنجرة.",
      "ضعي اللحم أو الدجاج فوقها ثم أضيفي الأرز.",
      "اسكبي المرق بحيث يغمر الأرز (لكل كوب أرز كوبين مرق).",
      "اطبخي حتى ينضج الأرز، ثم اقلبي الطنجرة للتقديم.",
    ],
  },
  {
    id: 2,
    title: "المسخن",
    image: "recipe_musakhan",
    description:
      "طبق تراثي فلسطيني مصنوع من خبز الطابون المغطى بالبصل المكرمل وزيت الزيتون والسماق، يُقدم مع الدجاج المشوي ويشتهر في موسم قطف الزيتون.",
    difficulty: "متوسطة",
    servings: "٤ أشخاص",
    time: "٤٥ دقيقة",
    ingredients: [
      "٤ أرغفة خبز طابون",
      "١ كيلو دجاج مشوي",
      "٤ بصلات كبيرة مكرملة",
      "زيت زيتون، سماق، ملح، فلفل",
      "صنوبر للتزيين",
    ],
    steps: [
      "كرملي البصل بزيت الزيتون مع السماق والملح.",
      "اشوي الدجاج حتى يصبح ذهبيًا وطريًا.",
      "ضعي الخبز في صينية وغطيه بالبصل مع القليل من المرق.",
      "أضيفي قطع الدجاج وزينيه بالصنوبر.",
    ],
  },
  {
    id: 4,
    title: "القدرة الفلسطينية",
    image: "recipe_qidra",
    description:
      "طبق تراثي من مدينة الخليل يتكون من الأرز والحمص والثوم واللحم أو الدجاج، يُطهى في قدر فخاري مع الكركم والبهارات الدافئة.",
    difficulty: "متوسطة",
    servings: "٦ أشخاص",
    time: "١ ساعة ١٥ دقيقة",
    ingredients: [
      "٢ كوب أرز",
      "١ كيلو لحم أو دجاج",
      "١ كوب حمص مسلوق",
      "٥ فصوص ثوم",
      "كركم، هيل، فلفل أسود، ملح",
    ],
    steps: [
      "اطبخي اللحم أو الدجاج مع الثوم والبهارات حتى ينضج.",
      "في قدر فخاري أو معدني، ضعي الأرز والحمص واللحم.",
      "أضيفي المرق حتى يغمر الأرز.",
      "اطبخي أو اخبزي حتى ينضج الأرز بالكامل.",
    ],
  },
  {
    id: 5,
    title: "المفتول",
    image: "recipe_meftoul",
    description:
      "طبق فلسطيني تقليدي يُحضّر من حبيبات القمح الملفوفة يدويًا (كسكس فلسطيني) تُبخر مع الحمص والخضار وتُقدم مع الدجاج والمرق المتبل.",
    difficulty: "متوسطة",
    servings: "٥ أشخاص",
    time: "١ ساعة ٣٠ دقيقة",
    ingredients: [
      "٢ كوب مفتول (كسكس فلسطيني)",
      "١ كيلو دجاج",
      "١ كوب حمص مسلوق",
      "٢ بصلة مفرومة",
      "صلصة طماطم، قرفة، بهارات مشكلة، ملح، فلفل",
    ],
    steps: [
      "اسلقي الدجاج مع البصل والبهارات حتى ينضج.",
      "بخري المفتول مع قليل من الزيت والمرق.",
      "اطبخي الحمص والخضار مع صلصة الطماطم في المرق.",
      "قدمي المفتول مع الحمص والدجاج والمرق.",
    ],
  },
  {
    id: 6,
    title: "المجدرة",
    image: "recipe_mujaddara",
    description:
      "طبق فلسطيني شعبي يجمع بين العدس والأرز أو البرغل ويُزين بالبصل المكرمل، يمتاز ببساطته وغناه بالقيمة الغذائية.",
    difficulty: "سهلة",
    servings: "٤ أشخاص",
    time: "٤٠ دقيقة",
    ingredients: [
      "١ كوب عدس بني",
      "١ كوب أرز أو برغل",
      "٢ بصلة مقطعة شرائح",
      "زيت زيتون، كمون، ملح",
    ],
    steps: [
      "اسلقي العدس حتى نصف استواء.",
      "أضيفي الأرز والبهارات واطبخي حتى ينضج.",
      "حمري البصل بزيت الزيتون حتى يصبح ذهبيًا.",
      "زيني الطبق بالبصل المكرمل عند التقديم.",
    ],
  },
  {
    id: 7,
    title: "الملوخية",
    image: "recipe_mulukhiyah",
    description:
      "حساء فلسطيني تقليدي مصنوع من أوراق الملوخية المفرومة مع مرق الدجاج أو اللحم، ويُقدم غالبًا مع الأرز والخبز.",
    difficulty: "متوسطة",
    servings: "٥ أشخاص",
    time: "٥٠ دقيقة",
    ingredients: [
      "٥٠٠ غرام ملوخية مفرومة",
      "١ كيلو دجاج أو لحم",
      "٥ فصوص ثوم مهروس",
      "كزبرة ناشفة، ملح، فلفل",
      "مرق دجاج أو لحم",
    ],
    steps: [
      "اسلقي الدجاج أو اللحم وحضري المرق.",
      "أضيفي الملوخية المفرومة إلى المرق واتركيها تغلي.",
      "قلبي الثوم مع الكزبرة الجافة بالزيت وأضيفيها على الحساء.",
      "قدميها مع الأرز والخبز.",
    ],
  },
  {
    id: 8,
    title: "البامية",
    image: "recipe_bamya",
    description:
      "طبق فلسطيني تقليدي من البامية المطبوخة مع صلصة الطماطم واللحم أو الدجاج، يُقدم مع الأرز أو الخبز.",
    difficulty: "سهلة",
    servings: "٤ أشخاص",
    time: "٤٥ دقيقة",
    ingredients: [
      "٥٠٠ غرام بامية",
      "٢ كوب طماطم مهروسة",
      "١ كيلو لحم أو دجاج",
      "ثوم، كزبرة ناشفة، ملح، فلفل",
    ],
    steps: [
      "اقلي الثوم والكزبرة الجافة بالزيت.",
      "أضيفي الطماطم المهروسة والبهارات واطبخي الصلصة.",
      "ضعي البامية واللحم واتركيها حتى تنضج.",
      "قدميها مع الأرز الأبيض.",
    ],
  },
  {
    id: 9,
    title: "صواني الباذنجان والبطاطا",
    image: "recipe_eggplant_potato_tray",
    description:
      "أطباق فلسطينية تقليدية تُحضر في الفرن من الباذنجان أو البطاطا أو خليط بينهما مع اللحم وصلصة الطماطم.",
    difficulty: "متوسطة",
    servings: "٦ أشخاص",
    time: "١ ساعة",
    ingredients: [
      "٢ حبة باذنجان",
      "٢ حبة بطاطا",
      "١/٢ كيلو لحم مفروم",
      "٢ كوب طماطم مهروسة",
      "بصل، بهارات مشكلة، زيت زيتون",
    ],
    steps: [
      "اقلي أو اشوي شرائح الباذنجان والبطاطا.",
      "حضري حشوة اللحم مع البصل والبهارات.",
      "رصي الخضار واللحم في صينية الفرن واسكبي صلصة الطماطم.",
      "اخبزي حتى تتجانس النكهات وتصبح ذهبية.",
    ],
  },
  {
    id: 10,
    title: "المحاشي وورق العنب",
    image: "recipe_mahashi_waraq",
    description:
      "أطباق محشوة بالأرز واللحم أو الخضار مثل الكوسا وورق العنب، مطبوخة بمرق غني بالبهارات.",
    difficulty: "متوسطة",
    servings: "٦ أشخاص",
    time: "١ ساعة ٣٠ دقيقة",
    ingredients: [
      "٥٠ ورقة عنب",
      "٤ حبات كوسا أو فلفل",
      "٢ كوب أرز",
      "١/٢ كيلو لحم مفروم",
      "بهارات مشكلة، ملح، فلفل",
    ],
    steps: [
      "حضري حشوة الأرز مع اللحم والبهارات.",
      "احشي الكوسا ولفي ورق العنب.",
      "رصيهم في الطنجرة وأضيفي المرق.",
      "اطبخي على نار هادئة حتى تنضج.",
    ],
  },
  {
    id: 11,
    title: "الفتة",
    image: "recipe_fatteh",
    description:
      "طبق فلسطيني شهي مصنوع من الخبز المحمص واللبن والحمص واللحم، يُقدم عادة في المناسبات أو الإفطار.",
    difficulty: "سهلة",
    servings: "٥ أشخاص",
    time: "٣٠ دقيقة",
    ingredients: [
      "٤ أرغفة خبز محمص",
      "٢ كوب حمص مسلوق",
      "٢ كوب لبن",
      "١/٢ كيلو لحم مفروم أو مسلوق",
      "ثوم، صنوبر، سمنة",
    ],
    steps: [
      "كسري الخبز المحمص وضعيه في طبق التقديم.",
      "أضيفي الحمص واللبن فوق الخبز.",
      "زيني باللحم المطبوخ والصنوبر المحمص.",
      "قدميها فورًا وهي دافئة.",
    ],
  },
  {
    id: 12,
    title: "الدجاج المشوي بالفرن",
    image: "recipe_roasted_chicken",
    description:
      "دجاج فلسطيني متبل بالبهارات وزيت الزيتون ومشوي في الفرن حتى يصبح طريًا وذهبي اللون، يُقدم مع الأرز أو البطاطا.",
    difficulty: "سهلة",
    servings: "٤ أشخاص",
    time: "١ ساعة",
    ingredients: [
      "١ دجاجة كاملة أو قطع دجاج",
      "زيت زيتون",
      "بهارات مشكلة، ملح، فلفل",
      "عصير ليمون، ثوم مهروس",
    ],
    steps: [
      "تتبيل الدجاج بالزيت والبهارات والثوم والليمون.",
      "ضعيه في الفرن حتى ينضج ويصبح ذهبي اللون.",
      "قدميه ساخنًا مع الأرز أو البطاطا المشوية.",
    ],
  },
  {
    id: 13,
    title: "فطائر السبانخ (المطبق)",
    image: "recipe_spinach_pie",
    description:
      "فطائر تراثية فلسطينية محشوة بالسبانخ المتبلة والبصل وزيت الزيتون، تُخبز حتى تصبح ذهبية ومقرمشة.",
    difficulty: "متوسطة",
    servings: "٦ أشخاص",
    time: "٤٥ دقيقة",
    ingredients: [
      "٢ كوب دقيق",
      "٢ كوب سبانخ مفروم",
      "١ بصلة مفرومة",
      "زيت زيتون، سماق، ملح، فلفل",
    ],
    steps: [
      "حضري العجينة واتركيها لتتخمر.",
      "اخلطي السبانخ مع البصل والبهارات والسماق.",
      "احشي العجينة وأغلقيها بشكل مثلثات.",
      "اخبزيها حتى تصبح ذهبية.",
    ],
  },
  {
    id: 14,
    title: "المعكرونة الفلسطينية",
    image: "recipe_pasta",
    description:
      "طبق فلسطيني بسيط مصنوع من المعكرونة وصلصة الطماطم والبهارات، يُقدم أحيانًا مع اللحم المفروم أو الخضار.",
    difficulty: "سهلة",
    servings: "٥ أشخاص",
    time: "٣٥ دقيقة",
    ingredients: [
      "٥٠٠ غرام معكرونة",
      "٢ كوب طماطم مهروسة",
      "١ بصلة مفرومة",
      "زيت زيتون، ملح، فلفل، بهارات",
      "لحم مفروم أو خضار اختيارية",
    ],
    steps: [
      "اسلقي المعكرونة حتى تنضج.",
      "حضري صلصة الطماطم بالزيت والبصل والبهارات.",
      "اخلطي المعكرونة مع الصلصة واللحم أو الخضار.",
      "قدميها ساخنة مع رشة جبن اختيارية.",
    ],
  },
];

export const RECIPES_EN: BaseRecipe[] = [
  {
    id: 1,
    title: "Maqluba",
    image: "recipe_maqluba",
    description:
      "A traditional Palestinian dish made with rice, fried eggplant, and potatoes with meat or chicken. It is flipped upside down when served, revealing rich layers of authentic flavors, often enjoyed at family gatherings and feasts.",
    difficulty: "Medium",
    servings: "4 Serves",
    time: "45 mins",
    ingredients: [
      "2 cups rice",
      "1 kg chicken or lamb",
      "2 fried eggplants",
      "1 fried potato",
      "Mixed spices, salt, pepper",
    ],
    steps: [
      "Boil the meat or chicken with spices until tender.",
      "Soak the rice for 30 minutes and drain.",
      "Place the fried eggplants and potatoes at the bottom of the pot.",
      "Layer the meat or chicken on top, followed by the rice.",
      "Pour broth over the rice (2 cups broth for every 1 cup rice).",
      "Cook until the rice is done, then flip the pot to serve.",
    ],
  },
  {
    id: 2,
    title: "Musakhan",
    image: "recipe_musakhan",
    description:
      "A traditional Palestinian dish made of taboon bread topped with caramelized onions, olive oil, and sumac, served with roasted chicken. It is especially popular during the olive harvest season.",
    difficulty: "Medium",
    servings: "4 Serves",
    time: "45 mins",
    ingredients: [
      "4 pieces of taboon bread",
      "1 kg roasted chicken",
      "4 large caramelized onions",
      "Olive oil, sumac, salt, pepper",
      "Pine nuts for garnish",
    ],
    steps: [
      "Caramelize the onions with olive oil, sumac, and salt.",
      "Roast the chicken until golden and tender.",
      "Place the bread in a tray and top with the onion mixture and a bit of broth.",
      "Add the roasted chicken pieces and garnish with pine nuts.",
    ],
  },
  {
    id: 4,
    title: "Qidra",
    image: "recipe_qidra",
    description:
      "A heritage dish from Hebron made with rice, chickpeas, garlic, and lamb or chicken, cooked in clay pots with turmeric and warm spices.",
    difficulty: "Medium",
    servings: "6 Serves",
    time: "1 hour 15 mins",
    ingredients: [
      "2 cups rice",
      "1 kg lamb or chicken",
      "1 cup boiled chickpeas",
      "5 garlic cloves",
      "Turmeric, cardamom, black pepper, salt",
    ],
    steps: [
      "Cook the meat or chicken with garlic and spices until tender.",
      "In a clay or metal pot, layer the rice, chickpeas, and meat.",
      "Add broth to cover the rice.",
      "Cook or bake until the rice is fully cooked.",
    ],
  },
  {
    id: 5,
    title: "Meftoul",
    image: "recipe_meftoul",
    description:
      "A traditional Palestinian couscous dish made from hand-rolled wheat grains steamed with chickpeas and vegetables, served with spiced chicken and aromatic broth.",
    difficulty: "Medium",
    servings: "5 Serves",
    time: "1 hour 30 mins",
    ingredients: [
      "2 cups Palestinian couscous (meftoul)",
      "1 kg chicken",
      "1 cup boiled chickpeas",
      "2 chopped onions",
      "Tomato paste, cinnamon, mixed spices, salt, pepper",
    ],
    steps: [
      "Boil the chicken with onions and spices until cooked.",
      "Steam the meftoul with a bit of oil and broth.",
      "Cook the chickpeas and vegetables with tomato paste in the broth.",
      "Serve the meftoul topped with chickpeas, vegetables, and chicken with broth on the side.",
    ],
  },
  {
    id: 6,
    title: "Mujaddara",
    image: "recipe_mujaddara",
    description:
      "A comforting Palestinian dish of lentils and rice or bulgur topped with caramelized onions, known for its simplicity and rich flavor.",
    difficulty: "Easy",
    servings: "4 Serves",
    time: "40 mins",
    ingredients: [
      "1 cup brown lentils",
      "1 cup rice or bulgur",
      "2 sliced onions",
      "Olive oil, cumin, salt",
    ],
    steps: [
      "Boil lentils until half-cooked.",
      "Add rice and spices, cook until tender.",
      "Fry onions in olive oil until golden and crispy.",
      "Serve mujaddara topped with fried onions.",
    ],
  },
  {
    id: 7,
    title: "Mulukhiyah",
    image: "recipe_mulukhiyah",
    description:
      "A traditional Palestinian soup made from finely chopped mulukhiyah leaves cooked in chicken or meat broth, served with rice and bread.",
    difficulty: "Medium",
    servings: "5 Serves",
    time: "50 mins",
    ingredients: [
      "500 g chopped mulukhiyah",
      "1 kg chicken or lamb",
      "5 crushed garlic cloves",
      "Dried coriander, salt, pepper",
      "Chicken or meat broth",
    ],
    steps: [
      "Boil the chicken or lamb and prepare the broth.",
      "Add the mulukhiyah leaves to the broth and simmer.",
      "Sauté garlic with dried coriander in oil and add to the soup.",
      "Serve with rice and bread.",
    ],
  },
  {
    id: 8,
    title: "Bamya",
    image: "recipe_bamya",
    description:
      "A Palestinian dish of okra cooked in tomato sauce with meat or chicken, served with rice or bread.",
    difficulty: "Easy",
    servings: "4 Serves",
    time: "45 mins",
    ingredients: [
      "500 g okra",
      "2 cups mashed tomatoes",
      "1 kg meat or chicken",
      "Garlic, dried coriander, salt, pepper",
    ],
    steps: [
      "Sauté garlic and dried coriander in oil.",
      "Add mashed tomatoes and spices, cook into a sauce.",
      "Add okra and meat, simmer until tender.",
      "Serve with white rice.",
    ],
  },
  {
    id: 9,
    title: "Eggplant & Potato Trays",
    image: "recipe_eggplant_potato_tray",
    description:
      "Traditional Palestinian oven-baked trays made with eggplant, potatoes, or a mix of both, layered with meat and tomato sauce.",
    difficulty: "Medium",
    servings: "6 Serves",
    time: "1 hour",
    ingredients: [
      "2 eggplants",
      "2 potatoes",
      "500 g minced meat",
      "2 cups mashed tomatoes",
      "Onion, mixed spices, olive oil",
    ],
    steps: [
      "Fry or roast the eggplant and potato slices.",
      "Prepare the meat filling with onions and spices.",
      "Layer vegetables and meat in a baking tray, pour tomato sauce on top.",
      "Bake until flavors combine and top turns golden.",
    ],
  },
  {
    id: 10,
    title: "Mahashi & Grape Leaves",
    image: "recipe_mahashi_waraq",
    description:
      "Stuffed vegetables and grape leaves filled with rice and meat or spiced rice, cooked in rich broth.",
    difficulty: "Medium",
    servings: "6 Serves",
    time: "1 hour 30 mins",
    ingredients: [
      "50 grape leaves",
      "4 zucchinis or bell peppers",
      "2 cups rice",
      "500 g minced meat",
      "Mixed spices, salt, pepper",
    ],
    steps: [
      "Prepare the rice filling with meat and spices.",
      "Stuff the zucchinis and roll the grape leaves.",
      "Arrange in a pot and cover with broth.",
      "Simmer on low heat until fully cooked.",
    ],
  },
  {
    id: 11,
    title: "Fatteh",
    image: "recipe_fatteh",
    description:
      "A beloved Palestinian dish made with toasted bread, yogurt, chickpeas, and meat, often served for breakfast or special occasions.",
    difficulty: "Easy",
    servings: "5 Serves",
    time: "30 mins",
    ingredients: [
      "4 pieces toasted bread",
      "2 cups boiled chickpeas",
      "2 cups yogurt",
      "500 g minced or boiled meat",
      "Garlic, pine nuts, ghee",
    ],
    steps: [
      "Break toasted bread and place it in a serving dish.",
      "Add chickpeas and yogurt on top.",
      "Garnish with cooked meat and toasted pine nuts.",
      "Serve immediately while warm.",
    ],
  },
  {
    id: 12,
    title: "Roasted Chicken",
    image: "recipe_roasted_chicken",
    description:
      "Palestinian-style chicken marinated with spices and olive oil, roasted in the oven until tender and golden, served with rice or potatoes.",
    difficulty: "Easy",
    servings: "4 Serves",
    time: "1 hour",
    ingredients: [
      "1 whole chicken or pieces",
      "Olive oil",
      "Mixed spices, salt, pepper",
      "Lemon juice, crushed garlic",
    ],
    steps: [
      "Marinate the chicken with oil, spices, garlic, and lemon.",
      "Roast in the oven until golden and fully cooked.",
      "Serve hot with rice or roasted potatoes.",
    ],
  },
  {
    id: 13,
    title: "Spinach Pies (Mutabbak)",
    image: "recipe_spinach_pie",
    description:
      "Traditional Palestinian pastries stuffed with seasoned spinach, onions, and olive oil, baked until golden and crispy.",
    difficulty: "Medium",
    servings: "6 Serves",
    time: "45 mins",
    ingredients: [
      "2 cups flour",
      "2 cups chopped spinach",
      "1 chopped onion",
      "Olive oil, sumac, salt, pepper",
    ],
    steps: [
      "Prepare the dough and let it rise.",
      "Mix spinach with onions, spices, and sumac.",
      "Fill the dough and fold into triangles.",
      "Bake until golden and crisp.",
    ],
  },
  {
    id: 14,
    title: "Palestinian Pasta",
    image: "recipe_pasta",
    description:
      "A simple Palestinian dish made with pasta, tomato sauce, and spices, sometimes served with minced meat or vegetables.",
    difficulty: "Easy",
    servings: "5 Serves",
    time: "35 mins",
    ingredients: [
      "500 g pasta",
      "2 cups mashed tomatoes",
      "1 chopped onion",
      "Olive oil, salt, pepper, spices",
      "Optional minced meat or vegetables",
    ],
    steps: [
      "Boil pasta until cooked.",
      "Prepare tomato sauce with oil, onions, and spices.",
      "Mix pasta with sauce and meat or vegetables.",
      "Serve hot with optional cheese topping.",
    ],
  },
];
