import { BaseRecipe } from "@/types/recipe.types";

export const SALADS_AR: BaseRecipe[] = [
  {
    id: 1,
    title: "سلطة الجرجير",
    image: "salad_rocket",
    description:
      "سلطة منعشة تعتمد على الجرجير الطازج وزيت الزيتون وعصير الليمون، تُقدَّم عادةً بجانب الأكلات المصرية.",
    time: "10 دقائق",
    difficulty: "سهل",
    servings: "4 أشخاص",
    ingredients: [
      "حزمة جرجير طازج",
      "2 ملعقة كبيرة زيت زيتون",
      "عصير ليمونة",
      "ملح حسب الرغبة",
    ],
    steps: [
      "اغسل الجرجير وصفيه.",
      "ضع الجرجير في وعاء التقديم.",
      "أضف زيت الزيتون وعصير الليمون ورشة ملح.",
      "قلّب وقدّمه فورًا.",
    ],
  },
  {
    id: 2,
    title: "سلطة الطحينة",
    image: "salad_tahini",
    description:
      "سلطة كريمية من الطحينة مع عصير الليمون والثوم، تُقدَّم غالبًا مع الفول والكباب.",
    time: "10 دقائق",
    difficulty: "سهل",
    servings: "4 أشخاص",
    ingredients: [
      "4 ملاعق كبيرة طحينة",
      "2 ملعقة كبيرة عصير ليمون",
      "1 فص ثوم مهروس",
      "ملح حسب الرغبة",
      "ماء لتخفيف القوام",
    ],
    steps: [
      "اخلط الطحينة مع عصير الليمون والثوم والملح.",
      "أضف الماء تدريجيًا حتى الحصول على قوام كريمي.",
      "قدّمها مباشرة مع الخبز أو الأطباق الرئيسية.",
    ],
  },
  {
    id: 3,
    title: "سلطة الباذنجان",
    image: "salad_eggplant",
    description:
      "سلطة باذنجان مشوي أو مقلي مع طماطم وبصل وفلفل رومي، تُقدَّم بجانب الأكلات المصرية التقليدية.",
    time: "20 دقيقة",
    difficulty: "متوسطة",
    servings: "4 أشخاص",
    ingredients: [
      "2 حبة باذنجان متوسطة",
      "1 حبة طماطم مقطعة",
      "1 بصلة متوسطة مقطعة",
      "1 فلفل رومي مقطع",
      "2 ملعقة كبيرة زيت زيتون",
      "ملح وفلفل حسب الرغبة",
    ],
    steps: [
      "اشوِ الباذنجان حتى يصبح لينًا، ثم قشره وقطّعه مكعبات.",
      "اخلط الباذنجان مع الطماطم والبصل والفلفل.",
      "أضف زيت الزيتون والملح والفلفل.",
      "قدّم السلطة فورًا أو بعد تبريدها قليلًا.",
    ],
  },
  {
    id: 4,
    title: "سلطة الطماطم والبصل",
    image: "salad_tomato_onion",
    description:
      "سلطة بسيطة ومنعشة من الطماطم والبصل والفلفل الرومي، مناسبة كإضافة لكل وجبة.",
    time: "10 دقائق",
    difficulty: "سهل",
    servings: "4 أشخاص",
    ingredients: [
      "2 حبة طماطم كبيرة مقطعة",
      "1 بصلة متوسطة مقطعة شرائح",
      "1 فلفل رومي مقطع",
      "2 ملعقة كبيرة عصير ليمون",
      "ملح وزيت زيتون حسب الرغبة",
    ],
    steps: [
      "اخلط الطماطم والبصل والفلفل في وعاء.",
      "أضف عصير الليمون والزيت والملح.",
      "قدّم السلطة فورًا.",
    ],
  },
  {
    id: 5,
    title: "سلطة الكرنب",
    image: "salad_cabbage",
    description:
      "سلطة كرنب مفروم مع جزر وخل وزيت، تُقدَّم بجانب الأطباق المصرية التقليدية.",
    time: "15 دقيقة",
    difficulty: "سهل",
    servings: "4 أشخاص",
    ingredients: [
      "1/2 رأس كرنب مفروم",
      "1 جزرة مبشورة",
      "2 ملعقة كبيرة خل أبيض",
      "2 ملعقة كبيرة زيت نباتي",
      "ملح وفلفل حسب الرغبة",
    ],
    steps: [
      "اخلط الكرنب والجزر في وعاء.",
      "أضف الخل والزيت والملح والفلفل.",
      "قلّب جيدًا وقدّم السلطة.",
    ],
  },
  {
    id: 6,
    title: "سلطة البطاطس",
    image: "salad_potato",
    description:
      "سلطة بطاطس مسلوقة مع مايونيز وخضروات مبشورة، تُقدَّم كطبق جانبي شهي.",
    time: "15 دقيقة",
    difficulty: "سهل",
    servings: "4 أشخاص",
    ingredients: [
      "3 حبات بطاطس متوسطة مسلوقة ومقطعة مكعبات",
      "2 ملعقة كبيرة مايونيز",
      "1 جزرة مبشورة",
      "ملح وفلفل حسب الرغبة",
    ],
    steps: [
      "اخلط البطاطس مع المايونيز والجزر.",
      "أضف الملح والفلفل حسب الرغبة.",
      "قدّم السلطة باردة.",
    ],
  },
  {
    id: 7,
    title: "سلطة الملفوف الأحمر والأخضر",
    image: "salad_mixed_cabbage",
    description:
      "سلطة ملونة من الملفوف الأحمر والأخضر مع جزر وزيت وليمون، منعشة وسهلة التحضير.",
    time: "10 دقائق",
    difficulty: "سهل",
    servings: "4 أشخاص",
    ingredients: [
      "1/2 رأس كرنب أخضر مفروم",
      "1/2 رأس كرنب أحمر مفروم",
      "1 جزرة مبشورة",
      "2 ملعقة كبيرة عصير ليمون",
      "2 ملعقة كبيرة زيت زيتون",
      "ملح وفلفل حسب الرغبة",
    ],
    steps: [
      "اخلط جميع المكونات في وعاء.",
      "أضف عصير الليمون والزيت والملح والفلفل.",
      "قدّم السلطة فورًا.",
    ],
  },
  {
    id: 8,
    title: "سلطة الجزر والذرة",
    image: "salad_carrot_corn",
    description:
      "سلطة بسيطة وسريعة من الجزر المبشور والذرة الحلوة مع مايونيز وعصير ليمون.",
    time: "10 دقائق",
    difficulty: "سهل",
    servings: "4 أشخاص",
    ingredients: [
      "2 جزرة مبشورة",
      "1 كوب ذرة مسلوقة أو معلبة",
      "2 ملعقة كبيرة مايونيز",
      "1 ملعقة كبيرة عصير ليمون",
      "ملح وفلفل حسب الرغبة",
    ],
    steps: [
      "اخلط الجزر والذرة في وعاء.",
      "أضف المايونيز وعصير الليمون والملح والفلفل.",
      "قلّب جيدًا وقدّم السلطة.",
    ],
  },
  {
    id: 9,
    title: "سلطة الخيار والنعناع",
    image: "salad_cucumber_mint",
    description:
      "سلطة منعشة من الخيار مع أوراق النعناع وعصير الليمون، مثالية لفصل الصيف.",
    time: "10 دقائق",
    difficulty: "سهل",
    servings: "4 أشخاص",
    ingredients: [
      "2 حبة خيار مقطعة شرائح",
      "1 ملعقة كبيرة نعناع طازج مفروم",
      "2 ملعقة كبيرة عصير ليمون",
      "ملح حسب الرغبة",
    ],
    steps: [
      "اخلط شرائح الخيار مع النعناع.",
      "أضف عصير الليمون والملح.",
      "قدّم السلطة مباشرة.",
    ],
  },
  {
    id: 10,
    title: "سلطة الفجل والبقدونس",
    image: "salad_radish_parsley",
    description:
      "سلطة حادة ومنعشة من الفجل المقطع والبقدونس مع عصير الليمون وزيت الزيتون.",
    time: "10 دقائق",
    difficulty: "سهل",
    servings: "4 أشخاص",
    ingredients: [
      "1 كوب فجل مقطع شرائح رفيعة",
      "1/2 كوب بقدونس مفروم",
      "2 ملعقة كبيرة عصير ليمون",
      "2 ملعقة كبيرة زيت زيتون",
      "ملح وفلفل حسب الرغبة",
    ],
    steps: [
      "اخلط الفجل مع البقدونس في وعاء.",
      "أضف عصير الليمون والزيت والملح والفلفل.",
      "قدّم السلطة مباشرة.",
    ],
  },
];

export const SALADS_EN: BaseRecipe[] = [
  {
    id: 1,
    title: "Rocket Salad",
    image: "salad_rocket",
    description:
      "A refreshing salad made with fresh arugula, olive oil, and lemon juice, usually served alongside Egyptian dishes.",
    time: "10 minutes",
    difficulty: "Easy",
    servings: "4 people",
    ingredients: [
      "1 bunch fresh arugula",
      "2 tbsp olive oil",
      "Juice of 1 lemon",
      "Salt to taste",
    ],
    steps: [
      "Wash and drain the arugula.",
      "Place the arugula in a serving bowl.",
      "Add olive oil, lemon juice, and a pinch of salt.",
      "Toss and serve immediately.",
    ],
  },
  {
    id: 2,
    title: "Tahini Salad",
    image: "salad_tahini",
    description:
      "A creamy salad made from tahini, lemon juice, and garlic, often served with fava beans and kebabs.",
    time: "10 minutes",
    difficulty: "Easy",
    servings: "4 people",
    ingredients: [
      "4 tbsp tahini",
      "2 tbsp lemon juice",
      "1 clove garlic, minced",
      "Salt to taste",
      "Water to adjust consistency",
    ],
    steps: [
      "Mix tahini with lemon juice, garlic, and salt.",
      "Gradually add water until creamy consistency is reached.",
      "Serve immediately with bread or main dishes.",
    ],
  },
  {
    id: 3,
    title: "Eggplant Salad",
    image: "salad_eggplant",
    description:
      "A salad of roasted or fried eggplant mixed with tomatoes, onions, and bell peppers, served with traditional Egyptian meals.",
    time: "20 minutes",
    difficulty: "Medium",
    servings: "4 people",
    ingredients: [
      "2 medium eggplants",
      "1 tomato, chopped",
      "1 medium onion, chopped",
      "1 bell pepper, chopped",
      "2 tbsp olive oil",
      "Salt and pepper to taste",
    ],
    steps: [
      "Roast the eggplants until soft, then peel and dice them.",
      "Mix eggplant with tomatoes, onions, and bell pepper.",
      "Add olive oil, salt, and pepper.",
      "Serve immediately or chilled.",
    ],
  },
  {
    id: 4,
    title: "Tomato and Onion Salad",
    image: "salad_tomato_onion",
    description:
      "A simple and refreshing salad made with tomatoes, onions, and bell peppers, suitable for any meal.",
    time: "10 minutes",
    difficulty: "Easy",
    servings: "4 people",
    ingredients: [
      "2 large tomatoes, chopped",
      "1 medium onion, sliced",
      "1 bell pepper, chopped",
      "2 tbsp lemon juice",
      "Salt and olive oil to taste",
    ],
    steps: [
      "Mix tomatoes, onions, and bell pepper in a bowl.",
      "Add lemon juice, oil, and salt.",
      "Serve fresh.",
    ],
  },
  {
    id: 5,
    title: "Cabbage Salad",
    image: "salad_cabbage",
    description:
      "A chopped cabbage salad with carrots, vinegar, and oil, often served alongside traditional Egyptian dishes.",
    time: "15 minutes",
    difficulty: "Easy",
    servings: "4 people",
    ingredients: [
      "1/2 head cabbage, shredded",
      "1 carrot, grated",
      "2 tbsp white vinegar",
      "2 tbsp vegetable oil",
      "Salt and pepper to taste",
    ],
    steps: [
      "Combine cabbage and carrots in a bowl.",
      "Add vinegar, oil, salt, and pepper.",
      "Toss well and serve.",
    ],
  },
  {
    id: 6,
    title: "Potato Salad",
    image: "salad_potato",
    description:
      "Boiled potatoes mixed with mayonnaise and grated vegetables, served as a delicious side dish.",
    time: "15 minutes",
    difficulty: "Easy",
    servings: "4 people",
    ingredients: [
      "3 medium boiled potatoes, diced",
      "2 tbsp mayonnaise",
      "1 carrot, grated",
      "Salt and pepper to taste",
    ],
    steps: [
      "Mix potatoes with mayonnaise and carrots.",
      "Season with salt and pepper.",
      "Serve chilled.",
    ],
  },
  {
    id: 7,
    title: "Mixed Cabbage Salad",
    image: "salad_mixed_cabbage",
    description:
      "A colorful salad made with red and green cabbage, carrots, lemon, and olive oil, refreshing and easy to prepare.",
    time: "10 minutes",
    difficulty: "Easy",
    servings: "4 people",
    ingredients: [
      "1/2 head green cabbage, shredded",
      "1/2 head red cabbage, shredded",
      "1 carrot, grated",
      "2 tbsp lemon juice",
      "2 tbsp olive oil",
      "Salt and pepper to taste",
    ],
    steps: [
      "Mix all ingredients in a bowl.",
      "Add lemon juice, oil, salt, and pepper.",
      "Serve immediately.",
    ],
  },
  {
    id: 8,
    title: "Carrot and Corn Salad",
    image: "salad_carrot_corn",
    description:
      "A quick and simple salad made with grated carrots, sweet corn, mayonnaise, and lemon juice.",
    time: "10 minutes",
    difficulty: "Easy",
    servings: "4 people",
    ingredients: [
      "2 grated carrots",
      "1 cup boiled or canned corn",
      "2 tbsp mayonnaise",
      "1 tbsp lemon juice",
      "Salt and pepper to taste",
    ],
    steps: [
      "Combine carrots and corn in a bowl.",
      "Add mayonnaise, lemon juice, salt, and pepper.",
      "Mix well and serve.",
    ],
  },
  {
    id: 9,
    title: "Cucumber and Mint Salad",
    image: "salad_cucumber_mint",
    description:
      "A refreshing salad made with cucumber slices, fresh mint, and lemon juice, perfect for summer.",
    time: "10 minutes",
    difficulty: "Easy",
    servings: "4 people",
    ingredients: [
      "2 cucumbers, sliced",
      "1 tbsp fresh mint, chopped",
      "2 tbsp lemon juice",
      "Salt to taste",
    ],
    steps: [
      "Mix cucumber slices with mint.",
      "Add lemon juice and salt.",
      "Serve immediately.",
    ],
  },
  {
    id: 10,
    title: "Radish and Parsley Salad",
    image: "salad_radish_parsley",
    description:
      "A sharp and refreshing salad made with sliced radishes, parsley, lemon juice, and olive oil.",
    time: "10 minutes",
    difficulty: "Easy",
    servings: "4 people",
    ingredients: [
      "1 cup radishes, thinly sliced",
      "1/2 cup chopped parsley",
      "2 tbsp lemon juice",
      "2 tbsp olive oil",
      "Salt and pepper to taste",
    ],
    steps: [
      "Mix radishes and parsley in a bowl.",
      "Add lemon juice, oil, salt, and pepper.",
      "Serve fresh.",
    ],
  },
];
