import { BaseRecipe } from "@/types/recipe.types";

export const DESSERTS_AR: BaseRecipe[] = [
  {
    id: 1,
    title: "كنافة نابلسية",
    image: "dessert_nabulsi_knafeh",
    description:
      "حلوى فلسطينية شهيرة من نابلس تُحضّر من عجينة الكنافة المقرمشة والجبن الحلو مع القطر، وتُقدَّم في المناسبات والأعياد.",
    time: "45 دقيقة",
    difficulty: "متوسطة",
    servings: "6 أشخاص",
    ingredients: [
      "500 غرام كنافة",
      "300 غرام جبنة عكاوي أو نابلسية",
      "1 كوب سمن أو زبدة مذابة",
      "2 كوب قطر (شيرة)",
      "فستق حلبي للتزيين",
    ],
    steps: [
      "نفتت الكنافة ونخلطها مع السمن المذاب.",
      "نضع نصف كمية الكنافة في صينية ونضغطها جيدًا.",
      "نضيف طبقة الجبن فوقها ثم نغطيها بالنصف الآخر من الكنافة.",
      "نخبزها حتى تكتسب لونًا ذهبيًا.",
      "نسكب القطر فوقها ونزين بالفستق الحلبي.",
    ],
  },
  {
    id: 2,
    title: "كنافة عربية",
    image: "dessert_arabic_knafeh",
    description:
      "نوع آخر من الكنافة الفلسطينية التقليدية، تُحضّر باستخدام السميد بدل الشعر وتُسقى بالقطر وتُزين بالفستق الحلبي.",
    time: "50 دقيقة",
    difficulty: "متوسطة",
    servings: "6 أشخاص",
    ingredients: [
      "2 كوب سميد خشن",
      "300 غرام جبن حلو",
      "1 كوب سمن",
      "2 كوب قطر",
      "فستق حلبي للتزيين",
    ],
    steps: [
      "نحمص السميد مع السمن حتى يصبح ذهبي اللون.",
      "نضع نصف الكمية في صينية ونسويها جيداً.",
      "نضيف طبقة الجبن ونغطيها بالنصف الآخر.",
      "نخبزها حتى تتحمر ثم نصب القطر فوقها.",
      "نزين بالفستق الحلبي ونقدمها ساخنة.",
    ],
  },
  {
    id: 4,
    title: "معمول",
    image: "dessert_maamoul",
    description:
      "حلوى تراثية فلسطينية تُحضّر من عجينة السميد أو الطحين محشوة بالتمر أو الجوز أو الفستق، وتُقدّم في الأعياد.",
    time: "1 ساعة",
    difficulty: "متوسطة",
    servings: "10 أشخاص",
    ingredients: [
      "3 كوب سميد",
      "1 كوب سمن",
      "1 كوب حليب",
      "حشوة تمر أو جوز أو فستق",
      "سكر بودرة للتزيين",
    ],
    steps: [
      "نخلط السميد مع السمن والحليب ونتركه يرتاح.",
      "نشكل العجينة ونحشيها بالتمر أو الجوز أو الفستق.",
      "نستخدم القوالب لتشكيل المعمول.",
      "نخبزه حتى يصبح ذهبي اللون.",
      "نرش السكر البودرة عند التقديم.",
    ],
  },
  {
    id: 5,
    title: "برازق",
    image: "dessert_barazek",
    description:
      "بسكويت مقرمش مغطى بالسمسم والفستق، من الحلويات الفلسطينية التقليدية المشهورة في الأعياد.",
    time: "35 دقيقة",
    difficulty: "سهلة",
    servings: "12 شخص",
    ingredients: [
      "2 كوب طحين",
      "1 كوب زبدة",
      "1 كوب سكر",
      "سمسم وفستق للتغطية",
    ],
    steps: [
      "نخلط الطحين مع السكر والزبدة لعمل عجينة طرية.",
      "نشكل أقراص صغيرة ونغمسها بالسمسم والفستق.",
      "نخبزها حتى تصبح ذهبية ومقرمشة.",
    ],
  },
  {
    id: 6,
    title: "كعك العيد",
    image: "dessert_eid_kaak",
    description:
      "كعك تقليدي يُحضّر في الأعياد الفلسطينية، محشو بالتمر أو الجوز أو بدون حشوة، ويُرش بالسكر البودرة.",
    time: "1 ساعة",
    difficulty: "متوسطة",
    servings: "10 أشخاص",
    ingredients: [
      "3 كوب طحين",
      "1 كوب سمن",
      "1 كوب حليب",
      "حشوة تمر أو جوز",
      "سكر بودرة للتزيين",
    ],
    steps: [
      "نخلط المكونات الجافة مع السمن والحليب.",
      "نشكل العجينة ونحشيها حسب الرغبة.",
      "نخبزها حتى تتحمر.",
      "نرش السكر البودرة ونقدمها.",
    ],
  },
  {
    id: 7,
    title: "مبروشة",
    image: "dessert_mabrousha",
    description:
      "حلوى فلسطينية مصنوعة من عجينة البسكويت المحشوة بالمربى، مشهورة ببساطتها ونكهتها البيتية.",
    time: "40 دقيقة",
    difficulty: "سهلة",
    servings: "8 أشخاص",
    ingredients: [
      "2 كوب طحين",
      "1 كوب زبدة",
      "1 كوب سكر",
      "1 كوب مربى مشمش أو فراولة",
    ],
    steps: [
      "نخلط الطحين مع السكر والزبدة لعمل عجينة.",
      "نفرد نصف العجينة في صينية ونضع المربى فوقها.",
      "نبشر النصف الآخر فوق المربى.",
      "نخبزها حتى تتحمر.",
    ],
  },
  {
    id: 8,
    title: "مقروطة",
    image: "dessert_maqrouda",
    description:
      "حلوى فلسطينية مصنوعة من السميد ومحشوة بالتمر أو الجوز، مشهورة بشكلها المستطيل المميز.",
    time: "50 دقيقة",
    difficulty: "متوسطة",
    servings: "8 أشخاص",
    ingredients: [
      "2 كوب سميد",
      "1 كوب طحين",
      "1 كوب سمن",
      "تمر معجون أو جوز للحشوة",
    ],
    steps: [
      "نخلط السميد والطحين مع السمن لعمل عجينة طرية.",
      "نفرد العجينة ونحشيها بالتمر أو الجوز ونلفها رول.",
      "نقطعها مستطيلات ونخبزها حتى تتحمر.",
    ],
  },
  {
    id: 9,
    title: "حلبة",
    image: "dessert_helbeh",
    description:
      "كيك فلسطيني بالسميد ونكهة الحلبة، يُسقى بالقطر ويُقدم دافئاً خاصة في الشتاء.",
    time: "35 دقيقة",
    difficulty: "سهلة",
    servings: "10 أشخاص",
    ingredients: [
      "2 كوب سميد",
      "1 كوب طحين",
      "1 كوب زيت نباتي",
      "حلبة مغلية",
      "2 كوب قطر",
    ],
    steps: [
      "نغلي الحلبة ونأخذ مائها للعجن.",
      "نخلط السميد والطحين والزيت مع ماء الحلبة.",
      "نصب الخليط في صينية ونخبز حتى تتحمر.",
      "نسكب القطر فوقها ونقدمها.",
    ],
  },
  {
    id: 10,
    title: "قطايف",
    image: "dessert_qatayef",
    description:
      "عجينة هشة تُحشى بالقشطة أو الجوز وتقلى أو تُشوى، وتُقدَّم عادة في رمضان.",
    time: "30 دقيقة",
    difficulty: "سهلة",
    servings: "8 أشخاص",
    ingredients: [
      "2 كوب طحين",
      "1 كوب ماء دافئ",
      "ملعقة صغيرة خميرة",
      "ملعقة صغيرة سكر",
      "حشوة: قشطة أو جوز أو مكسرات أو تمر",
      "قطر للتقديم",
    ],
    steps: [
      "نخلط مكونات العجينة ونتركها لتختمر 30 دقيقة.",
      "نصب دوائر صغيرة على صاج ساخن ونطهو حتى تظهر الفقاعات.",
      "نحشي الأقراص بالقشطة أو الجوز ونغلقها.",
      "نقليها أو نحمرها بالفرن.",
      "نغمسها في القطر قبل التقديم.",
    ],
  },
  {
    id: 11,
    title: "عوامة",
    image: "dessert_awameh",
    description:
      "كرات عجين مقلية تُغمس بالقطر، مقرمشة من الخارج وطرية من الداخل.",
    time: "20 دقيقة",
    difficulty: "سهلة",
    servings: "6 أشخاص",
    ingredients: [
      "2 كوب طحين",
      "1 كوب ماء",
      "ملعقة صغيرة خميرة",
      "ملعقة صغيرة سكر",
      "زيت للقلي",
      "قطر للتقديم",
    ],
    steps: [
      "نخلط الطحين والماء والخميرة والسكر ونتركها لتختمر.",
      "نشكل كرات صغيرة من العجين.",
      "نقلي الكرات في زيت ساخن حتى تتحمر.",
      "نغمسها مباشرة في القطر ونقدمها ساخنة.",
    ],
  },
  {
    id: 12,
    title: "هريسة",
    image: "dessert_hareeseh",
    description: "كيك سميد مشرب بالقطر ومحشو أحياناً بجوز الهند أو المكسرات.",
    time: "35 دقيقة",
    difficulty: "سهلة",
    servings: "10 أشخاص",
    ingredients: [
      "2 كوب سميد",
      "1 كوب سكر",
      "1 كوب لبن زبادي",
      "نصف كوب جوز هند (اختياري)",
      "علبة قشطة",
      "قطر للتسقية",
    ],
    steps: [
      "نخلط السميد مع السكر واللبن وجوز الهند والقشطة.",
      "نصب الخليط في صينية مدهونة بالسمن.",
      "نقطعها مربعات ونزينها بلوز أو جوز.",
      "نخبزها حتى تتحمر.",
      "نسكب القطر فوقها بعد إخراجها من الفرن.",
    ],
  },

  {
    id: 3,
    title: "كنافة كذابة",
    image: "dessert_fake_knafeh",
    description:
      "كنافة سريعة التحضير تستخدم خبز التوست بدل عجينة الكنافة، تُعتبر وصفة منزلية اقتصادية وسهلة.",
    time: "30 دقيقة",
    difficulty: "سهلة",
    servings: "6 أشخاص",
    ingredients: [
      "10 شرائح خبز توست",
      "300 غرام جبنة حلوة",
      "1 كوب سمن أو زبدة",
      "2 كوب قطر",
    ],
    steps: [
      "نفتت خبز التوست ونحمصه بالسمن.",
      "نضع نصف الكمية في صينية.",
      "نضيف الجبن ثم نغطيه بباقي الخبز.",
      "نخبزها حتى تتحمر ونضيف القطر عند التقديم.",
    ],
  },
];

export const DESSERTS_EN: BaseRecipe[] = [
  {
    id: 1,
    title: "Nabulsi Knafeh",
    image: "dessert_nabulsi_knafeh",
    description:
      "A famous Palestinian dessert from Nablus made with crispy shredded pastry and sweet cheese soaked in sugar syrup, traditionally served during special occasions and holidays.",
    time: "45 min",
    difficulty: "Medium",
    servings: "6 people",
    ingredients: [
      "500g shredded kataifi pastry",
      "300g Akkawi or Nabulsi cheese",
      "1 cup melted butter or ghee",
      "2 cups sugar syrup",
      "Pistachios for garnish",
    ],
    steps: [
      "Shred the pastry and mix with melted butter.",
      "Press half of the pastry into a baking tray.",
      "Add the cheese layer and cover with the remaining pastry.",
      "Bake until golden brown.",
      "Pour sugar syrup on top and garnish with pistachios.",
    ],
  },
  {
    id: 2,
    title: "Arabic Knafeh",
    image: "dessert_arabic_knafeh",
    description:
      "A traditional Palestinian version of knafeh made with semolina instead of shredded pastry, soaked in syrup and topped with pistachios.",
    time: "50 min",
    difficulty: "Medium",
    servings: "6 people",
    ingredients: [
      "2 cups coarse semolina",
      "300g sweet cheese",
      "1 cup ghee",
      "2 cups sugar syrup",
      "Pistachios for garnish",
    ],
    steps: [
      "Toast semolina with ghee until golden.",
      "Press half into a baking tray.",
      "Add cheese layer and cover with remaining semolina.",
      "Bake until golden brown, then drizzle with syrup.",
      "Top with pistachios before serving.",
    ],
  },

  {
    id: 4,
    title: "Maamoul",
    image: "dessert_maamoul",
    description:
      "A traditional Palestinian pastry made from semolina or flour dough filled with dates, walnuts, or pistachios, commonly prepared for Eid holidays.",
    time: "1 hour",
    difficulty: "Medium",
    servings: "10 people",
    ingredients: [
      "3 cups semolina",
      "1 cup ghee",
      "1 cup milk",
      "Date, walnut, or pistachio filling",
      "Powdered sugar for garnish",
    ],
    steps: [
      "Mix semolina with ghee and milk, let rest.",
      "Shape dough and fill with desired filling.",
      "Use special molds to shape maamoul.",
      "Bake until golden brown.",
      "Dust with powdered sugar before serving.",
    ],
  },
  {
    id: 5,
    title: "Barazek",
    image: "dessert_barazek",
    description:
      "A crunchy Palestinian sesame and pistachio cookie, traditionally served during celebrations and holidays.",
    time: "35 min",
    difficulty: "Easy",
    servings: "12 people",
    ingredients: [
      "2 cups flour",
      "1 cup butter",
      "1 cup sugar",
      "Sesame seeds and pistachios for coating",
    ],
    steps: [
      "Mix flour, sugar, and butter to form soft dough.",
      "Shape into small discs and coat with sesame and pistachios.",
      "Bake until golden and crispy.",
    ],
  },
  {
    id: 6,
    title: "Eid Kaak",
    image: "dessert_eid_kaak",
    description:
      "Traditional Palestinian Eid cookies filled with dates or walnuts, dusted with powdered sugar and served during celebrations.",
    time: "1 hour",
    difficulty: "Medium",
    servings: "10 people",
    ingredients: [
      "3 cups flour",
      "1 cup ghee",
      "1 cup milk",
      "Date or walnut filling",
      "Powdered sugar for garnish",
    ],
    steps: [
      "Mix dry ingredients with ghee and milk.",
      "Shape and fill with desired filling.",
      "Bake until golden.",
      "Dust with powdered sugar before serving.",
    ],
  },
  {
    id: 7,
    title: "Mabrousha",
    image: "dessert_mabrousha",
    description:
      "A Palestinian jam-filled dessert made from buttery dough, known for its homemade flavor and simple preparation.",
    time: "40 min",
    difficulty: "Easy",
    servings: "8 people",
    ingredients: [
      "2 cups flour",
      "1 cup butter",
      "1 cup sugar",
      "1 cup apricot or strawberry jam",
    ],
    steps: [
      "Mix flour, sugar, and butter to form dough.",
      "Spread half in a baking tray and add jam.",
      "Grate remaining dough over the jam layer.",
      "Bake until golden brown.",
    ],
  },
  {
    id: 8,
    title: "Maqrouda",
    image: "dessert_maqrouda",
    description:
      "A traditional Palestinian semolina dessert filled with dates or walnuts, cut into rectangular pieces and baked.",
    time: "50 min",
    difficulty: "Medium",
    servings: "8 people",
    ingredients: [
      "2 cups semolina",
      "1 cup flour",
      "1 cup ghee",
      "Date or walnut filling",
    ],
    steps: [
      "Mix semolina and flour with ghee to form soft dough.",
      "Roll out dough, fill with dates or walnuts, and shape into rolls.",
      "Cut into rectangles and bake until golden.",
    ],
  },
  {
    id: 9,
    title: "Helbeh",
    image: "dessert_helbeh",
    description:
      "A Palestinian semolina cake flavored with fenugreek seeds, soaked in sugar syrup, and often enjoyed warm during winter.",
    time: "35 min",
    difficulty: "Easy",
    servings: "10 people",
    ingredients: [
      "2 cups semolina",
      "1 cup flour",
      "1 cup vegetable oil",
      "Boiled fenugreek water",
      "2 cups sugar syrup",
    ],
    steps: [
      "Boil fenugreek seeds and use the water for mixing.",
      "Mix semolina, flour, and oil with fenugreek water.",
      "Pour into tray and bake until golden.",
      "Soak with sugar syrup before serving.",
    ],
  },
  {
    id: 10,
    title: "Qatayef",
    image: "dessert_qatayef",
    description:
      "Soft stuffed pancakes filled with cream, nuts, or dates, fried or baked, and popular during Ramadan.",
    time: "30 min",
    difficulty: "Easy",
    servings: "8 people",
    ingredients: [
      "2 cups flour",
      "1 cup warm water",
      "1 tsp yeast",
      "1 tsp sugar",
      "Filling: cream, nuts, or dates",
      "Sugar syrup for serving",
    ],
    steps: [
      "Mix batter ingredients and let rise for 30 minutes.",
      "Pour small circles on a hot skillet until bubbles appear.",
      "Fill with cream or nuts and seal edges.",
      "Fry or bake until golden brown.",
      "Dip in syrup before serving.",
    ],
  },
  {
    id: 11,
    title: "Awameh (Luqaimat)",
    image: "dessert_awameh",
    description:
      "Crispy fried dough balls soaked in sugar syrup, crunchy outside and soft inside, widely enjoyed in Palestinian cuisine.",
    time: "20 min",
    difficulty: "Easy",
    servings: "6 people",
    ingredients: [
      "2 cups flour",
      "1 cup water",
      "1 tsp yeast",
      "1 tsp sugar",
      "Oil for frying",
      "Sugar syrup for serving",
    ],
    steps: [
      "Mix flour, water, yeast, and sugar, then let rise.",
      "Shape into small balls.",
      "Fry in hot oil until golden brown.",
      "Dip in syrup and serve hot.",
    ],
  },
  {
    id: 12,
    title: "Hareeseh (Semolina Cake)",
    image: "dessert_hareeseh",
    description:
      "A semolina cake soaked in sugar syrup, sometimes enriched with coconut or nuts, commonly served in Palestinian households.",
    time: "35 min",
    difficulty: "Easy",
    servings: "10 people",
    ingredients: [
      "2 cups semolina",
      "1 cup sugar",
      "1 cup yogurt",
      "1/2 cup coconut (optional)",
      "1 can cream",
      "Sugar syrup for soaking",
    ],
    steps: [
      "Mix semolina, sugar, yogurt, coconut, and cream.",
      "Pour into greased baking tray.",
      "Cut into squares and top with almonds or walnuts.",
      "Bake until golden brown.",
      "Pour syrup over while hot.",
    ],
  },
  {
    id: 3,
    title: "Fake Knafeh",
    image: "dessert_fake_knafeh",
    description:
      "A quick homemade knafeh variation using toasted bread instead of shredded pastry, ideal for an easy and budget-friendly dessert.",
    time: "30 min",
    difficulty: "Easy",
    servings: "6 people",
    ingredients: [
      "10 slices of white bread",
      "300g sweet cheese",
      "1 cup butter or ghee",
      "2 cups sugar syrup",
    ],
    steps: [
      "Shred bread and toast with butter.",
      "Place half in a baking tray.",
      "Add cheese layer and cover with remaining bread.",
      "Bake until golden and pour syrup on top before serving.",
    ],
  },
];
